Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2022-12, with the labels that each got.

#237 EL-504 take II - last piece of content for service not applicable page
  app/views/referrals/show.html.slim
  config/locales/en.yml
Labels: Approved

#220 EL-494 separate client and partner questions
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/concerns/session_persistable_for_partner.rb
  app/forms/dependants_form.rb
  app/forms/partner_details_form.rb
  app/forms/proceeding_type_form.rb
  app/lib/applicant_case_details_section.rb
  app/lib/check_answers_fields.yml
  app/lib/partner_section.rb
  app/lib/steps_helper.rb
  app/services/check_answers/applicant_section.rb
  app/services/submit_dependants_service.rb
  app/services/submit_partner_service.rb
  app/services/submit_proceedings_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/dependants.html.slim
  app/views/estimate_flow/partner_details.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/features/dependants_pages_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/property_page_spec.rb
  spec/features/provider_users_page_spec.rb
  spec/features/result_page_spec.rb
  spec/services/submit_partner_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved

#239 EL-511: Housing benefit and adjust all benefits check answers
  app/controllers/benefits_controller.rb
  app/controllers/flow/handler.rb
  app/forms/housing_benefit_details_form.rb
  app/forms/housing_benefit_form.rb
  app/lib/check_answers_fields.yml
  app/lib/income_section.rb
  app/models/benefit_model.rb
  app/models/calculation_result.rb
  app/models/estimate_model.rb
  app/services/cfe_param_builders/state_benefits.rb
  app/services/check_answers/section_lister_service.rb
  app/services/submit_benefits_service.rb
  app/views/benefits/_form.html.slim
  app/views/estimate_flow/forms/_housing_benefit.html.slim
  app/views/estimate_flow/forms/_housing_benefit_details.html.slim
  app/views/estimate_flow/housing_benefit.html.slim
  app/views/estimate_flow/housing_benefit_details.html.slim
  app/views/estimates/check_answers.html.slim
  config/locales/en.yml
  spec/features/change_employment_type_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/housing_benefit_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/services/submit_benefits_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#235 EL-507: more precise sections
  app/controllers/check_answers_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/controllers/check_partner_benefits_answers_controller.rb
  app/services/check_answers/section_id_finder.rb
  spec/features/vehicle_page_spec.rb
  spec/services/check_answers/section_id_finder_spec.rb
Labels: Approved, UAT

#241 EL-514 hide partner
  app/services/check_answers/property_section.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved, UAT

#243 EL-528 fix up service name in cookie banner
  app/views/layouts/_cookie_banner.html.slim
  config/locales/en.yml
  spec/features/cookies_spec.rb
Labels: Approved, UAT

#246 re-enable partner functionality on UAT
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Ready For Review

#240 EL-517: Partner housing benefit
  app/controllers/flow/handler.rb
  app/forms/partner_housing_benefit_details_form.rb
  app/forms/partner_housing_benefit_form.rb
  app/lib/check_answers_fields.yml
  app/lib/income_section.rb
  app/lib/partner_income_section.rb
  app/models/estimate_model.rb
  app/services/cfe_param_builders/state_benefits.rb
  app/services/check_answers/section_id_finder.rb
  app/services/submit_partner_service.rb
  app/views/estimate_flow/partner_housing_benefit.html.slim
  app/views/estimate_flow/partner_housing_benefit_details.html.slim
  config/locales/en.yml
  spec/features/check_answers_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_housing_benefit_pages_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/support/form_helpers.rb
Labels: Approved, UAT

#244 EL-522 upgrade ruby to version 3.1.3
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Approved, UAT

#236 EL-495 add partner dependants section into journey
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/dependant_details_form.rb
  app/forms/partner_dependant_details_form.rb
  app/forms/partner_details_form.rb
  app/lib/applicant_case_details_section.rb
  app/lib/check_answers_fields.yml
  app/lib/partner_section.rb
  app/models/estimate_model.rb
  app/services/cfe_param_builders/dependants.rb
  app/services/check_answers/applicant_section.rb
  app/services/check_answers/section_id_finder.rb
  app/services/submit_dependants_service.rb
  app/services/submit_partner_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/forms/_dependant_details.html.slim
  app/views/estimate_flow/partner_dependant_details.html.slim
  app/views/estimate_flow/partner_details.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/housing_benefit_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_dependants_pages_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_housing_benefit_pages_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/services/submit_dependants_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#257 EL-533: Only submit employment data if client is employed
  Gemfile.lock
  app/services/submit_employment_income_service.rb
Labels: Approved, UAT

#261 EL-525 part one - rework applicant spec (and re-ordered form validation)
  app/forms/applicant_form.rb
  spec/features/applicant_page_spec.rb
Labels: Ready For Review

#263 EL-525 rework results spec
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/system/outgoings_page_spec.rb
Labels: Approved

#258 EL-527: Update content
  app/views/estimate_flow/_partner_property_sidebar.html.slim
  app/views/estimate_flow/_property_sidebar.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_details.html.slim
  app/views/shared/_sidebar_with_date.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#266 EL-525 create full journey method to DRY up feature specs
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/housing_benefit_page_spec.rb
  spec/features/other_income_page_spec.rb
  spec/features/outgoings_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_dependants_pages_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_housing_benefit_pages_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/support/form_helpers.rb
  spec/support/navigation_helpers.rb
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: question, Approved

#273 EL-555 add date to provider question screen
  app/views/provider_users/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#272 EL-565: smarter number fields
  app/forms/base_assets_form.rb
  app/forms/base_property_entry_form.rb
  app/forms/client_property_entry_form.rb
  app/forms/dependant_details_form.rb
  app/forms/employment_form.rb
  app/forms/other_income_form.rb
  app/forms/outgoings_form.rb
  app/helpers/application_helper.rb
  app/services/check_answers/other_section.rb
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_dependant_details.html.slim
  app/views/estimate_flow/forms/_property_entry.html.slim
  config/initializers/attribute_types.rb
  config/locales/en.yml
  spec/features/assets_page_spec.rb
  spec/features/dependant_details_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/result_page_spec.rb
Labels: Approved, UAT

#270 El 522 internal route
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Ready For Review

#271 EL-559 rework housing costs help text
  app/views/estimate_flow/forms/_outgoings.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#288 EL-558 Add approval step before production deploy
  .circleci/config.yml
Labels: Approved

#274 EL-556: New dependant helptext
  app/views/estimate_flow/forms/_dependant_details.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#290 EL-558 cope/retry with invalid JSON responses from CFE
  app/lib/cfe_connection.rb
Labels: Approved

#294 update MoJ compliant badge
  README.md
Labels: Approved

#267 EL-532 add 'blind' component for disregarded benefits
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_add_benefit_form.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/shared/_disregarded_benefits.html.slim
  app/views/shared/_three_headings.html.slim
  config/locales/en.yml
  spec/features/benefits_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/support/form_helpers.rb
Labels: Approved, UAT

#298 Grafana dashboard moved here from environments repo
  .circleci/config.yml
  infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
Labels: Approved

#302 EL-575: Separate out headings from content in sidebar
  app/views/shared/_sidebar_with_date.html.slim
Labels: Approved, UAT

#299 EL-572: Add distinct page titles for every page
  app/lib/check_answers_fields.yml
  app/services/check_answers/section_lister_service.rb
  app/views/accessibilities/show.html.slim
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/cookies/show.html.slim
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/case_details.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/housing_benefit.html.slim
  app/views/estimate_flow/housing_benefit_details.html.slim
  app/views/estimate_flow/other_income.html.slim
  app/views/estimate_flow/outgoings.html.slim
  app/views/estimate_flow/partner.html.slim
  app/views/estimate_flow/partner_assets.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/estimate_flow/partner_dependant_details.html.slim
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimate_flow/partner_employment.html.slim
  app/views/estimate_flow/partner_housing_benefit.html.slim
  app/views/estimate_flow/partner_housing_benefit_details.html.slim
  app/views/estimate_flow/partner_other_income.html.slim
  app/views/estimate_flow/partner_outgoings.html.slim
  app/views/estimate_flow/partner_property.html.slim
  app/views/estimate_flow/partner_property_entry.html.slim
  app/views/estimate_flow/partner_vehicle.html.slim
  app/views/estimate_flow/partner_vehicle_details.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_details.html.slim
  app/views/estimates/check_answers.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  app/views/partner_benefits/edit.html.slim
  app/views/partner_benefits/new.html.slim
  app/views/privacies/show.html.slim
  app/views/provider_users/show.html.slim
  app/views/referrals/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#293 EL-562 update income labels and spacing
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/forms/_employment.html.slim
  config/locales/en.yml
Labels: Approved, UAT
