Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2022-11, with the labels that each got.

#129 El 386 send other income to CFE
  app/lib/cfe_connection.rb
  app/models/calculation_result.rb
  app/services/submit_irregular_income_service.rb
  spec/features/employment_page_spec.rb
  spec/features/monthly_income_page_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/system/assets_page_spec.rb
  spec/unit/cfe_connection_spec.rb
Labels: Approved, UAT

#143 EL-435 re-order property prompt options to match prototype
  app/helpers/build_estimates_helper.rb
  app/views/shared/_sidebar_with_date.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#132 EL-427 change confirmation panel to a neutral blue colour
  app/assets/stylesheets/results.scss
  app/models/calculation_result.rb
  app/views/estimates/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#149 EL-407: Specify adult and child dependants
  app/controllers/estimate_flow_controller.rb
  app/controllers/flow/dependant_details_handler.rb
  app/controllers/flow/dependants_handler.rb
  app/forms/applicant_form.rb
  app/forms/dependant_details_form.rb
  app/forms/dependants_form.rb
  app/lib/applicant_case_details_section.rb
  app/lib/cfe_connection.rb
  app/lib/check_answers_fields.yml
  app/models/estimate_model.rb
  app/services/submit_dependants_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/check_answers.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/dependants.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/dependants_pages_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/result_page_spec.rb
  spec/services/submit_dependants_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/applicant_page_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/check_answers_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#147 EL-437 Prompt for employment income frequency using radio buttons
  app/views/estimate_flow/employment.html.slim
  spec/features/employment_page_spec.rb
  spec/features/result_page_spec.rb
  spec/system/employment_page_spec.rb
Labels: Approved, UAT

#150 EL-407 bugfix update link to direct user to specific page
  config/locales/en.yml
Labels: bug, Ready For Review

#151 Refactor check answers page out of Wizard loop
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/flow/check_answers_handler.rb
  app/lib/capital_section.rb
  app/views/estimates/_check_answer.html.slim
  app/views/estimates/_money_check_answer.html.slim
  app/views/estimates/_two_column_check_answer.html.slim
  app/views/estimates/check_answers.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/check_answers_page_spec.rb
  spec/system/accessibility_spec.rb
Labels: Approved

#131 EL-413 use redis session store
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/attribute_types.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
Labels: Approved, UAT

#162 add github action to delete UAT release on merge or close of PR
  .github/actions/delete-uat-release/action.yml
  .github/workflows/delete_uat_release.yml
Labels: Approved

#135 EL-431 non-property Assets in dispute
  app/forms/assets_form.rb
  app/lib/cfe_connection.rb
  app/services/submit_assets_service.rb
  app/views/estimate_flow/assets.html.slim
  config/locales/en.yml
  spec/features/assets_page_spec.rb
Labels: Approved, UAT

#165 Remove delete UAT job from circleci
  .circleci/config.yml
  bin/delete_uat_deployment
Labels: Approved

#136 EL-433: Show SMOD disregards in capital summary table
  app/models/calculation_result.rb
  app/views/estimates/_client_capital_table.html.slim
  config/locales/en.yml
  spec/features/result_page_spec.rb
Labels: Approved

#154 EL-439: Fix variously broken back buttons
  app/helpers/application_helper.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/case_details.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/dependants.html.slim
  app/views/estimate_flow/outgoings.html.slim
Labels: Approved, UAT

#137 EL-430: Add SMOD checkbox to vehicles page
  app/forms/vehicle_details_form.rb
  app/lib/cfe_connection.rb
  app/services/submit_vehicle_service.rb
  app/views/estimate_flow/vehicle_details.html.slim
  config/locales/en.yml
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
Labels: Approved

#155 EL-388: Complex check answers behaviour
  app/controllers/benefits_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/lib/steps_helper.rb
  spec/features/change_employment_type_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/support/form_helpers.rb
Labels: Approved, UAT

#168 EL-444: Fix bug in check answers benefits section logic
  app/services/check_answers/section_lister_service.rb
  spec/features/check_answers_page_spec.rb
  spec/support/form_helpers.rb
Labels: Approved, UAT

#169 EL-445: Fix 'delete the only benefit' flow
  app/controllers/benefits_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/helpers/application_helper.rb
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  spec/features/check_answers_page_spec.rb
Labels: Approved, UAT

#178 EL-446 Don't display dependants questions when user is passported
  app/lib/applicant_case_details_section.rb
  spec/features/applicant_page_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/support/form_helpers.rb
  spec/system/assets_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#180 Add extra employment tests
  spec/features/employment_page_spec.rb
Labels: Ready For Review

#182 EL-475: Add new partner questions
  app/controllers/estimate_flow_controller.rb
  app/controllers/flow/applicant_handler.rb
  app/controllers/flow/partner_handler.rb
  app/forms/applicant_form.rb
  app/forms/partner_form.rb
  app/lib/applicant_case_details_section.rb
  app/lib/check_answers_fields.yml
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/partner.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/partner_page_spec.rb
  spec/support/form_helpers.rb
Labels: Approved, UAT

#194 Add a test for the anchor during the vehicle check answers loop
  spec/features/vehicle_page_spec.rb
Labels: Approved

#181 EL-454: Feedback links
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  config/locales/en.layouts.yml
  config/locales/en.yml
Labels: Approved, UAT

#163 EL-419 Subject matter of dispute.
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/width.scss
  app/controllers/check_answers_controller.rb
  app/controllers/flow/asset_handler.rb
  app/forms/assets_form.rb
  app/forms/property_entry_form.rb
  app/forms/vehicle_details_form.rb
  app/lib/cfe_connection.rb
  app/lib/check_answers_fields.yml
  app/models/calculation_result.rb
  app/services/check_answers/applicant_section.rb
  app/services/check_answers/other_income_section.rb
  app/services/check_answers/other_section.rb
  app/services/check_answers/property_section.rb
  app/services/check_answers/relevant_section_finder_service.rb
  app/services/check_answers/section_lister_service.rb
  app/services/check_answers/vehicle_section.rb
  app/services/submit_assets_service.rb
  app/services/submit_vehicle_service.rb
  app/views/estimate_flow/_property_sidebar.html.slim
  app/views/estimate_flow/_smod_help.html.slim
  app/views/estimate_flow/_vehicle_sidebar.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_details.html.slim
  app/views/estimates/_check_answer.html.slim
  app/views/estimates/_client_capital_table.html.slim
  app/views/estimates/_money_check_answer.html.slim
  app/views/estimates/check_answers.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  config/locales/en.yml
  package.json
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/other_income_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/support/form_helpers.rb
  spec/system/assets_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
  spec/unit/cfe_connection_spec.rb
  yarn.lock
Labels: Approved, UAT

#198 Add CFEP URLs to EFE UAT and STAGING environments
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Ready For Review

#199 Re-add conditional logic around partner field display
  app/services/check_answers/applicant_section.rb
  spec/features/applicant_page_spec.rb
Labels: Ready For Review

#179 EL-450: Compensate for CFE's over-eager pensioner disregard
  app/models/calculation_result.rb
  spec/features/result_page_spec.rb
Labels: Approved, UAT

#195 EL-478: BUG - check answers flow leads back to the benefits page
  app/controllers/benefits_controller.rb
Labels: Approved, UAT

#203 EL-455 Deploy to prod namespace
  .circleci/config.yml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
Labels: Approved

#196 EL-469: Send partner data to CFE
  app/forms/client_assets_form.rb
  app/lib/cfe_connection.rb
  app/services/base_cfe_service.rb
  app/services/cfe_param_builders/capitals.rb
  app/services/cfe_param_builders/employments.rb
  app/services/cfe_param_builders/irregular_income.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/cfe_param_builders/state_benefits.rb
  app/services/cfe_param_builders/vehicles.rb
  app/services/cfe_service.rb
  app/services/submit_applicant_service.rb
  app/services/submit_assets_service.rb
  app/services/submit_benefits_service.rb
  app/services/submit_dependants_service.rb
  app/services/submit_employment_income_service.rb
  app/services/submit_irregular_income_service.rb
  app/services/submit_partner_service.rb
  app/services/submit_proceedings_service.rb
  app/services/submit_regular_transactions_service.rb
  app/services/submit_vehicle_service.rb
  spec/features/assets_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/services/submit_partner_service_spec.rb
  spec/unit/cfe_connection_spec.rb
Labels: Approved

#183 El 442 display calculations on results page
  app/models/calculation_result.rb
  app/views/estimates/_client_capital_table.html.slim
  config/locales/en.yml
  spec/features/assets_page_spec.rb
  spec/features/dependants_pages_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/other_income_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
Labels: Approved, UAT

#201 EL-483: Add flipper
  .env.sample
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/lib/applicant_case_details_section.rb
  config/initializers/flipper.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
  spec/features/applicant_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/support/form_helpers.rb
Labels: Approved, UAT

#214 add sentry dsn for production
  helm_deploy/laa-estimate-eligibility/values-production.yaml
Labels: Approved

#204 EL-477 add employed attribute to applicant
  app/lib/cfe_connection.rb
  app/services/submit_applicant_service.rb
  spec/features/applicant_page_spec.rb
  spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
Labels: Approved, UAT

#215 add google analytics code to prod
  helm_deploy/laa-estimate-eligibility/values-production.yaml
Labels: Approved

#216 EL-447: Use headless tests
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/error_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved

#222 DRY partner flag usage
  spec/features/applicant_page_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_benefits_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_other_income_page_spec.rb
  spec/features/partner_outgoings_page_spec.rb
  spec/features/partner_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/rails_helper.rb
  spec/support/form_helpers.rb
Labels: Approved

#221 EL-322: Update footer
  app/controllers/privacies_controller.rb
  app/views/layouts/_footer.html.slim
  app/views/privacies/show.html.slim
  config/locales/en.layouts.yml
  config/locales/en.yml
  config/routes.rb
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#219 EL-497: Add new static error pages
  public/404.html
  public/422.html
  public/500.html
Labels: Approved, UAT

#217 EL-379 Change service name
  app/views/cookies/show.html.slim
  app/views/layouts/application.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#223 EL-510 start page copy
  app/views/estimates/print.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#226 EL-499: Kubernetes probes
  app/controllers/status_controller.rb
  app/lib/cfe_connection.rb
  app/services/health_check_service.rb
  config/routes.rb
  helm_deploy/laa-estimate-eligibility/templates/deployment.yaml
  spec/requests/statuses_controller_spec.rb
Labels: Approved, UAT

#234 Use correct endpoint in new tests
  spec/requests/statuses_controller_spec.rb
Labels: Approved

#230 EL-338 link to user survey in Beta banner
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#232 EL-513 don't show partner_other_income section when no partner
  app/services/check_answers/section_lister_service.rb
Labels: Approved, UAT

#218 EL-458: Add modsec
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved, UAT

#193 EL-472 new partner property questions
  app/controllers/flow/handler.rb
  app/forms/base_property_entry_form.rb
  app/forms/client_property_entry_form.rb
  app/forms/partner_property_entry_form.rb
  app/forms/partner_property_form.rb
  app/forms/property_form.rb
  app/lib/capital_section.rb
  app/lib/check_answers_fields.yml
  app/lib/partner_capital_section.rb
  app/models/estimate_model.rb
  app/services/check_answers/property_section.rb
  app/services/submit_assets_service.rb
  app/views/estimate_flow/_partner_property_sidebar.html.slim
  app/views/estimate_flow/forms/_property.html.slim
  app/views/estimate_flow/forms/_property_entry.html.slim
  app/views/estimate_flow/partner_property.html.slim
  app/views/estimate_flow/partner_property_entry.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/partner_assets_page_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/support/form_helpers.rb
  spec/system/assets_page_spec.rb
Labels: Approved, UAT

#225 EL-504 client content
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_partner_property_sidebar.html.slim
  app/views/estimate_flow/_property_sidebar.html.slim
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/case_details.html.slim
  app/views/estimate_flow/partner.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimates/show.html.slim
  app/views/provider_users/show.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#233 EL-505 rename application
  .circleci/config.yml
  bin/uat_deployment
  helm_deploy/laa-estimate-eligibility/Chart.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
Labels: Approved, UAT

#238 Bugfix: Rename chart for ingress name
  bin/uat_deployment
  helm_deploy/laa-estimate-eligibility/Chart.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
Labels: Ready For Review
