Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2022-09, with the labels that each got.

#19 Remove RSpec github action
  .github/workflows/rspec-tests.yml
Labels: Approved

#14 Change dependabot schedule to weekly
  .github/dependabot.yml
Labels: Approved

#2 Try out usage of Wicked::Wizard gem
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/build_estimates_controller.rb
  app/controllers/pages_controller.rb
  app/forms/intro_form.rb
  app/forms/monthly_income_form.rb
  app/helpers/build_estimates_helper.rb
  app/validators/at_least_one_item_validator.rb
  app/views/build_estimates/intro.html.erb
  app/views/build_estimates/monthly_income.html.erb
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property.html.erb
  app/views/pages/home.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/welcome_spec.rb
Labels: Approved

#25 Add MoJ compliancy badge
  README.md
Labels: Approved

#23 Rubocop-govuk and ERB lint checks
  .circleci/config.yml
  .erb-lint.yml
  .github/workflows/format-code.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/build_estimates_controller.rb
  app/forms/intro_form.rb
  app/forms/monthly_income_form.rb
  app/helpers/build_estimates_helper.rb
  app/validators/at_least_one_item_validator.rb
  app/views/build_estimates/intro.html.erb
  app/views/build_estimates/monthly_income.html.erb
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  config/routes.rb
  spec/system/welcome_spec.rb
Labels: Approved

#28 Remove database dependency
  .circleci/config.yml
  Gemfile
  app/models/application_record.rb
  bin/setup
  config/application.rb
  spec/rails_helper.rb
Labels: Approved

#29 EL-282 remove database (from environment files)
  config/environments/development.rb
  config/environments/production.rb
Labels: Approved

#16 Investigate rails conventions around :js tag
  spec/features/welcome_spec.rb
  spec/rails_helper.rb
Labels: Approved

#27 Propshaft assets in test mode
  .circleci/config.yml
  README.md
  config/application.rb
Labels: Approved

#35 EL-260 sentry integration
  .env.sample
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  config/application.rb
  config/initializers/sentry.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#37 add helm instructions to the README.md
  README.md
Labels: Approved

#38 Restrict ECR and deploy tasks to main branch
  .circleci/config.yml
Labels: Approved

#26 Add Brakeman checks
  .circleci/config.yml
  .github/workflows/brakeman-analysis.yml
  config/environments/production.rb
Labels: Approved

#45 Remove force-ssl config as we are behind an SSL reverse proxy
  config/environments/production.rb
Labels: Ready For Review

#48 Add test for results page defect
  spec/features/applicant_page_spec.rb
Labels: Ready For Review

#46 Bugfix: Formatting of monetary values on final results page
  app/views/build_estimates/results.html.erb
  spec/features/applicant_page_spec.rb
Labels: bug, Approved

#47 Bug: assets form can't ask second home question if no first home owned
  app/views/build_estimates/assets.html.erb
  spec/features/assets_page_spec.rb
  spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_fill_in_the_assets_questions_and_get_to_results.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_submit_non-zero_savings_and_investments.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_submit_second_property.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/sets_error_on_assets_form.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_no_property/doesnt_show_second_property_question.yml
  spec/fixtures/vcr_cassettes/Assets_Page/with_no_property/shows_the_correct_page.yml
Labels: bug, Ready For Review

#30 EL-321 Ephemeral deployments to uat
  .circleci/config.yml
  bin/uat_deployment
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#49 Bugfix: Remove duplication from CircleCI workflow and fix staging deploy issue
  .circleci/config.yml
  bin/uat_deployment
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
Labels: Ready For Review

#50 EL-334 add service start page in slim.html
  Gemfile
  Gemfile.lock
  app/controllers/start_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  config/locales/layouts.yml
  config/routes.rb
Labels: Ready For Review
