Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2022-10, with the labels that each got.

#61 Fix typo in name of k8s namespace in helm readme section
  README.md
Labels: documentation, Ready For Review

#63 Bugfix: update deployment script to fix k8s naming length issue
  bin/uat_deployment
Labels: Ready For Review

#51 EL-358: Update income page
  Gemfile.lock
  app/controllers/build_estimates_controller.rb
  app/controllers/flow/monthly_income_handler.rb
  app/controllers/flow/outgoings_handler.rb
  app/forms/monthly_income_form.rb
  app/lib/cfe_connection.rb
  app/views/build_estimates/_sidebar_with_date.html.slim
  app/views/build_estimates/assets.html.erb
  app/views/build_estimates/monthly_income.html.erb
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property.html.erb
  app/views/build_estimates/property_entry.html.erb
  app/views/build_estimates/results.html.erb
  app/views/build_estimates/vehicle.html.erb
  app/views/layouts/_sidebar.html.slim
  app/views/layouts/application.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/monthly_income_page_spec.rb
  spec/fixtures/vcr_cassettes/Income_Page/behaves_appropriately_if_a_field_is_unchecked_after_a_value_is_entered.yml
  spec/support/form_helpers.rb
  spec/system/monthly_income_page_spec.rb
Labels: enhancement, ruby, Approved, UAT

#71 Convert money_input template from HTML to SLIM
  app/views/build_estimates/_money_input.html.erb
  app/views/build_estimates/assets.html.erb
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property_entry.html.erb
  app/views/shared/_money_input.html.slim
  app/views/shared/_money_input_with_hint.html.slim
  config/locales/en.yml
Labels: Approved

#70 EL-380 Add circleci job to delete helm deployments
  .circleci/config.yml
  bin/delete_uat_deployment
Labels: Approved

#72 EL-332 Add delete script and job to circleci
  .circleci/config.yml
  bin/delete_ecr_images
Labels: Approved

#73 EL-380 bugfix: Remove purge flag as it is now the default for delete commands
  bin/delete_uat_deployment
Labels: Approved

#74 EL-380 (further fix)add required hyphen on namespace flag
  bin/delete_uat_deployment
Labels: Approved

#67 EL-323: Cookie banner
  app/controllers/cookies_controller.rb
  app/views/cookies/show.html.slim
  app/views/layouts/_analytics.html.slim
  app/views/layouts/_cookie_banner.html.slim
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  config/application.rb
  config/locales/en.yml
  config/locales/layouts.yml
  config/routes.rb
  spec/controllers/cookies_controller_spec.rb
  spec/features/cookies_spec.rb
Labels: Approved, UAT

#53 EL-363 initial branching question
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/panel-grey.scss
  app/controllers/provider_users_controller.rb
  app/controllers/referrals_controller.rb
  app/models/provider_user.rb
  app/views/provider_users/show.html.slim
  app/views/referrals/show.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/property_page_spec.rb
  spec/features/provider_users_page_spec.rb
  spec/requests/provider_users_spec.rb
  spec/requests/referrals_spec.rb
  spec/requests/start_spec.rb
Labels: Approved, UAT

#62 EL-360: Main Dwelling
  app/controllers/build_estimates_controller.rb
  app/controllers/flow/applicant_handler.rb
  app/controllers/flow/asset_handler.rb
  app/controllers/flow/monthly_income_handler.rb
  app/controllers/flow/outgoings_handler.rb
  app/controllers/flow/property_entry_handler.rb
  app/controllers/flow/property_handler.rb
  app/controllers/flow/summary_handler.rb
  app/controllers/flow/vehicle_handler.rb
  app/forms/property_entry_form.rb
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/property.html.erb
  app/views/build_estimates/property.html.slim
  app/views/build_estimates/property_entry.html.erb
  app/views/build_estimates/property_entry.html.slim
  config/locales/en.yml
  spec/features/property_page_spec.rb
Labels: Approved, UAT

#56 EL-351: Employment questions page
  app/controllers/build_estimates_controller.rb
  app/controllers/flow/employment_handler.rb
  app/forms/employment_form.rb
  app/helpers/steps_helper.rb
  app/lib/cfe_connection.rb
  app/models/estimate_data.rb
  app/views/build_estimates/employment.html.slim
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/summary.html.erb
  app/views/layouts/application.html.slim
  config/locales/en.yml
  spec/features/employment_page_spec.rb
  spec/fixtures/vcr_cassettes/Employment_Page/accessibility/has_no_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/accessibility/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Employment_Page/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Employment_Page/has_no_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/shows_the_correct_page.yml
  spec/system/employment_page_spec.rb
Labels: Approved, UAT

#69 EL-382: Graceful error handling
  app/lib/cfe_connection.rb
  public/500.html
  public/gds-transport-bold.woff2
  public/gds-transport-light.woff2
  spec/system/error_page_spec.rb
  spec/unit/cfe_connection_spec.rb
Labels: Approved, UAT

#76 Refactor CFE_HOST to make it more flexible
  .env.sample
  app/lib/cfe_connection.rb
  config/application.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
Labels: Approved

#85 Bugfix: Stop us sending student loan values if loan box is unchecked
  app/controllers/flow/monthly_income_handler.rb
  spec/features/monthly_income_page_spec.rb
Labels: Approved

#52 EL-361 Complete Vehicle Screens
  app/controllers/build_estimates_controller.rb
  app/controllers/flow/property_handler.rb
  app/controllers/flow/vehicle/age_handler.rb
  app/controllers/flow/vehicle/finance_handler.rb
  app/controllers/flow/vehicle/owned_handler.rb
  app/controllers/flow/vehicle/value_handler.rb
  app/controllers/flow/vehicle_handler.rb
  app/forms/vehicle_age_form.rb
  app/forms/vehicle_finance_form.rb
  app/forms/vehicle_form.rb
  app/forms/vehicle_value_form.rb
  app/helpers/steps_helper.rb
  app/lib/cfe_connection.rb
  app/models/estimate_data.rb
  app/views/build_estimates/applicant.html.erb
  app/views/build_estimates/assets.html.erb
  app/views/build_estimates/assets.html.slim
  app/views/build_estimates/employment.html.slim
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property.html.slim
  app/views/build_estimates/property_entry.html.slim
  app/views/build_estimates/summary.html.erb
  app/views/build_estimates/vehicle.html.erb
  app/views/build_estimates/vehicle.html.slim
  app/views/build_estimates/vehicle_age.html.slim
  app/views/build_estimates/vehicle_finance.html.slim
  app/views/build_estimates/vehicle_value.html.slim
  app/views/layouts/application.html.slim
  app/views/provider_users/show.html.slim
  app/views/referrals/show.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_age_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_age_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_finance_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_finance_form/passes_accessibility_in_error_state_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_after_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_value_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_value_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/skips_questions_when_no_selected.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/when_vehicle_is_in_scope/when_in_regular_use/asks_all_the_questions.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/when_vehicle_is_in_scope/without_regular_usage/asks_no_more_questions.yml
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/system/applicant_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#84 EL-350 Add simple case details page to flow with just 2 proceeding types
  app/controllers/build_estimates_controller.rb
  app/controllers/flow/case_details_handler.rb
  app/forms/proceeding_type_form.rb
  app/helpers/steps_helper.rb
  app/lib/cfe_connection.rb
  app/views/build_estimates/case_details.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/monthly_income_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/provider_users_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Applicant_Page/applicant_page_flow/dependants_field/submits_dependants.yml
  spec/fixtures/vcr_cassettes/Applicant_Page/applicant_page_flow/passporting/when_passporting/has_a_back_pointer_to_the_applicant_page.yml
  spec/fixtures/vcr_cassettes/Applicant_Page/applicant_page_flow/passporting/when_passporting/skips_income_and_outgoings.yml
  spec/fixtures/vcr_cassettes/Applicant_Page/applicant_page_flow/passporting/without_passporting/has_a_back_pointer_to_the_applicant_page.yml
  spec/fixtures/vcr_cassettes/Applicant_Page/applicant_page_flow/passporting/without_passporting/shows_income.yml
  spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/accessibility/has_no_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/accessibility/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Employment_Page/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Employment_Page/has_no_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Income_Page/behaves_appropriately_if_a_field_is_unchecked_after_a_value_is_entered.yml
  spec/fixtures/vcr_cassettes/Income_Page/handles_student_finance_friends_or_family_and_maintenance.yml
  spec/fixtures/vcr_cassettes/Income_Page/shows_the_correct_page.yml
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_age_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_age_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_finance_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_finance_form/passes_accessibility_in_error_state_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_after_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_value_form/passes_accessibility_check.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/accessibility/vehicle_value_form/passes_accessibility_including_errors.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/has_a_back_link_to_the_property_input_form.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/sets_error_on_vehicle_form.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_no_property/when_vehicle_is_in_scope/when_in_regular_use/asks_all_the_questions.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/when_selecting_property/has_a_back_link_to_the_property_input_form.yml
  spec/support/form_helpers.rb
  spec/system/assets_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#82 EL-377: Use a forgiving, nicely formatted money input
  app/forms/assets_form.rb
  app/forms/employment_form.rb
  app/forms/monthly_income_form.rb
  app/forms/outgoings_form.rb
  app/forms/property_entry_form.rb
  app/forms/vehicle_finance_form.rb
  app/forms/vehicle_value_form.rb
  app/helpers/application_helper.rb
  app/views/shared/_money_input.html.slim
  app/views/shared/_money_input_with_hint.html.slim
  config/initializers/attribute_types.rb
  spec/features/assets_page_spec.rb
  spec/features/employment_page_spec.rb
Labels: Approved

#83 EL-387: Add phase banner
  app/views/layouts/application.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#86 EL-389 Warn if user enters negative (net) income
  app/forms/employment_form.rb
  config/locales/en.yml
  spec/features/employment_page_spec.rb
Labels: Approved, UAT

#87 EL-390 Sidebar styling and navigation
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/sidebar.scss
  app/views/build_estimates/_sidebar_with_date.html.slim
  app/views/build_estimates/assets.html.slim
  app/views/build_estimates/case_details.html.slim
  app/views/build_estimates/employment.html.slim
  app/views/build_estimates/monthly_income.html.slim
  app/views/build_estimates/outgoings.html.erb
  app/views/build_estimates/property.html.slim
  app/views/build_estimates/property_entry.html.slim
  app/views/build_estimates/vehicle.html.slim
  app/views/build_estimates/vehicle_age.html.slim
  app/views/build_estimates/vehicle_finance.html.slim
  app/views/build_estimates/vehicle_value.html.slim
  app/views/layouts/_sidebar.html.slim
  app/views/shared/_sidebar_with_date.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#81 EL-375: Spike results screen
  app/controllers/application_controller.rb
  app/controllers/build_estimates_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/flow/summary_handler.rb
  app/helpers/steps_helper.rb
  app/lib/cfe_connection.rb
  app/models/calculation_result.rb
  app/views/build_estimates/results.html.erb
  app/views/build_estimates/summary.html.erb
  app/views/estimates/show.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/result_page_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#65 EL-366 simple check answers
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/flow/check_answers_handler.rb
  app/controllers/flow/summary_handler.rb
  app/forms/employment_form.rb
  app/helpers/application_helper.rb
  app/helpers/build_estimates_helper.rb
  app/helpers/steps_helper.rb
  app/models/estimate_data.rb
  app/models/estimate_model.rb
  app/views/estimate_flow/_check_answer.html.slim
  app/views/estimate_flow/_money_check_answer.html.slim
  app/views/estimate_flow/applicant.html.erb
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/case_details.html.slim
  app/views/estimate_flow/check_answers.html.slim
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/monthly_income.html.slim
  app/views/estimate_flow/outgoings.html.erb
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/summary.html.erb
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_age.html.slim
  app/views/estimate_flow/vehicle_finance.html.slim
  app/views/estimate_flow/vehicle_value.html.slim
  app/views/shared/_sidebar_with_date.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Check_Answers_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/check_answers_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#92 EL-404: Fix double-reporting of monthly income
  app/controllers/flow/monthly_income_handler.rb
  spec/features/monthly_income_page_spec.rb
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#101 EL-403: Enforce explicit l10n in tests
  app/views/cookies/show.html.slim
  config/environments/test.rb
  config/locales/en.layouts.yml
Labels: Approved

#102 EL-374 add slim-lint to CI pipeline
  .circleci/config.yml
  .slim-lint.yml
  app/views/cookies/show.html.slim
  app/views/estimate_flow/_money_check_answer.html.slim
  app/views/estimate_flow/_property_sidebar.html.slim
  app/views/estimate_flow/_vehicle_sidebar.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/case_details.html.slim
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/monthly_income.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_age.html.slim
  app/views/estimate_flow/vehicle_finance.html.slim
  app/views/estimate_flow/vehicle_value.html.slim
  app/views/estimates/show.html.slim
  app/views/layouts/_analytics.html.slim
  app/views/layouts/_cookie_banner.html.slim
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  app/views/shared/_sidebar_with_date.html.slim
  app/views/start/index.html.slim
Labels: Approved

#95 el399 add missing error message
  config/locales/en.yml
Labels: Approved

#107 Fix sidebar slimdentation
  app/views/shared/_sidebar_with_date.html.slim
Labels: Ready For Review

#106 EL-342 branching coverage
  app/controllers/flow/employment_handler.rb
  spec/controllers/cookies_controller_spec.rb
  spec/features/assets_page_spec.rb
  spec/spec_helper.rb
  spec/unit/cfe_connection_spec.rb
Labels: Approved

#88 EL-365: Check answers
  app/controllers/check_answers_controller.rb
  app/controllers/flow/check_answers_handler.rb
  app/helpers/application_helper.rb
  app/helpers/steps_helper.rb
  app/models/estimate_model.rb
  app/presenters/check_answers_fields.yml
  app/presenters/check_answers_presenter.rb
  app/views/estimate_flow/_check_answer.html.slim
  app/views/estimate_flow/_money_check_answer.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/check_answers.html.slim
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/monthly_income.html.slim
  app/views/estimate_flow/outgoings.html.erb
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/summary.html.erb
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_age.html.slim
  app/views/estimate_flow/vehicle_finance.html.slim
  app/views/estimate_flow/vehicle_value.html.slim
  config/locales/en.yml
  spec/features/vehicle_page_spec.rb
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#111 EL-415: Remove irrelevant guidance
  app/views/estimate_flow/case_details.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#116 Refactor of StepsHelper into 3 independent sections
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/flow/monthly_income_handler.rb
  app/controllers/flow/outgoings_handler.rb
  app/helpers/application_helper.rb
  app/helpers/steps_helper.rb
  app/lib/applicant_case_details_section.rb
  app/lib/capital_section.rb
  app/lib/income_section.rb
  app/lib/steps_helper.rb
  app/presenters/check_answers_presenter.rb
  spec/features/monthly_income_page_spec.rb
  spec/system/accessibility_spec.rb
Labels: Approved

#108 EL 383 single call to CFE
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/flow/applicant_handler.rb
  app/controllers/flow/asset_handler.rb
  app/controllers/flow/case_details_handler.rb
  app/controllers/flow/employment_handler.rb
  app/controllers/flow/outgoings_handler.rb
  app/controllers/flow/property_entry_handler.rb
  app/controllers/flow/property_handler.rb
  app/controllers/flow/vehicle/finance_handler.rb
  app/controllers/flow/vehicle/owned_handler.rb
  app/controllers/flow/vehicle/value_handler.rb
  app/lib/cfe_connection.rb
  app/services/base_cfe_service.rb
  app/services/cfe_service.rb
  app/services/submit_applicant_service.rb
  app/services/submit_assets_service.rb
  app/services/submit_dependants_service.rb
  app/services/submit_employment_income_service.rb
  app/services/submit_irregular_income_service.rb
  app/services/submit_proceedings_service.rb
  app/services/submit_regular_transactions_service.rb
  app/services/submit_vehicle_service.rb
  app/views/estimate_flow/check_answers.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/case_details_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/monthly_income_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/provider_users_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
  spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
  spec/fixtures/vcr_cassettes/Income_Page/handles_student_finance_friends_or_family_and_maintenance.yml
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/rails_helper.rb
  spec/services/submit_dependants_service_spec.rb
  spec/services/submit_irregular_income_service_spec.rb
  spec/services/submit_vehicle_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/unit/cfe_connection_spec.rb
Labels: Approved

#113 EL-393: Remove partner question
  app/forms/applicant_form.rb
  app/views/estimate_flow/applicant.html.slim
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/monthly_income_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/support/form_helpers.rb
  spec/system/assets_page_spec.rb
  spec/system/check_answers_page_spec.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#96 EL-376 complete results screen with client outgoings and capital
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/results.scss
  app/controllers/estimates_controller.rb
  app/helpers/application_helper.rb
  app/models/calculation_result.rb
  app/views/estimates/show.html.slim
  config/locales/en.yml
  spec/factories/api_results.rb
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/support/factory_bot.rb
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#121 EL-352 create benefits
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/button-as-link.scss
  app/controllers/application_controller.rb
  app/controllers/benefits_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/flow/benefits_handler.rb
  app/forms/benefits_form.rb
  app/helpers/application_helper.rb
  app/lib/cfe_connection.rb
  app/lib/income_section.rb
  app/models/benefit_model.rb
  app/services/cfe_service.rb
  app/services/submit_benefits_service.rb
  app/views/benefits/_form.html.slim
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/estimate_flow/benefits.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/applicant_page_spec.rb
  spec/features/benefits_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/result_page_spec.rb
  spec/services/submit_benefits_service_spec.rb
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#110 EL-359: Client outgoings page
  app/controllers/flow/outgoings_handler.rb
  app/forms/outgoings_form.rb
  app/lib/cfe_connection.rb
  app/presenters/check_answers_fields.yml
  app/presenters/check_answers_presenter.rb
  app/views/estimate_flow/outgoings.html.erb
  app/views/estimate_flow/outgoings.html.slim
  config/locales/en.yml
  spec/features/monthly_income_page_spec.rb
  spec/features/outgoings_page_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#122 EL-414: Add print results screen
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/print.scss
  app/controllers/estimates_controller.rb
  app/views/estimates/_client_capital_table.html.slim
  app/views/estimates/_client_income_table.html.slim
  app/views/estimates/_client_outgoings_table.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  app/views/layouts/print_application.html.slim
  config/locales/en.yml
  config/routes.rb
  public/crest.svg
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#118 EL-416: Check outgoings answers
  app/lib/income_section.rb
  app/presenters/check_answers_fields.yml
  app/views/estimate_flow/_two_column_check_answer.html.slim
  app/views/estimate_flow/check_answers.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#104 EL-406 return to same section
  app/controllers/check_answers_controller.rb
  app/lib/check_answers_fields.yml
  app/presenters/check_answers_presenter.rb
  app/services/check_answers/relevant_section_finder_service.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/check_answers.html.slim
Labels: Approved, UAT

#130 EL-420 change check your answers heading
  config/locales/en.yml
  spec/features/assets_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#127 EL-417 new assets page without checkboxes
  app/forms/assets_form.rb
  app/lib/check_answers_fields.yml
  app/services/check_answers/section_lister_service.rb
  app/services/submit_assets_service.rb
  app/views/estimate_flow/assets.html.slim
  app/views/estimates/_client_capital_table.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/assets_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/features/vehicle_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/forms/assets_form_spec.rb
  spec/support/form_helpers.rb
  spec/system/accessibility_spec.rb
  spec/system/assets_page_spec.rb
  spec/system/check_answers_page_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#124 EL-411: Check benefits answers
  app/controllers/benefits_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/helpers/application_helper.rb
  app/lib/check_answers_fields.yml
  app/models/benefit_model.rb
  app/services/check_answers/section_lister_service.rb
  app/views/benefits/_form.html.slim
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_money_check_answer.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/check_answers.html.slim
  config/routes.rb
  spec/features/benefits_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/result_page_spec.rb
  spec/support/form_helpers.rb
  spec/system/employment_page_spec.rb
  spec/system/monthly_income_page_spec.rb
  spec/system/outgoings_page_spec.rb
Labels: Approved, UAT

#142 EL-434: Request search engines do not index
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  public/robots.txt
Labels: Ready For Review
