Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-07, with the labels that each got.

#786 EL-1003: Allow Blazer to override CSP settings
  config/blazer.yml
Labels: Approved

#783 EL-1004: Fix typo in instant sessions and add spec
  spec/factories/session.rb
  spec/features/instant_sessions_spec.rb
Labels: Approved, UAT

#784 EL-1006: Add percentage signs to percentages on check answers page
  app/lib/check_answers_fields.yml
  app/views/estimates/_check_answer.html.slim
  app/views/estimates/_check_answers_table.html.slim
  spec/views/check_answers_page/client_content/property_spec.rb
  spec/views/check_answers_page/partner_content/property_spec.rb
Labels: Approved, UAT

#772 EL-988: pdf metadata
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/estimates_controller.rb
  app/services/pdf_service.rb
Labels: Approved, UAT

#775 EL-984 Pensioner disregard alert
  app/controllers/controlled_work_document_selections_controller.rb
  app/views/controlled_work_document_selections/new.html.slim
  app/views/shared/_banner.html.slim
  config/locales/en.yml
  spec/forms/controlled_work_document_selection_spec.rb
Labels: Approved

#788 EL-1010: Incorrect wording on partner additional property screen
  config/locales/en.yml
Labels: Approved, UAT

#789 EL-999: e2e-ify all remaining end_to_end specs
  spec/end_to_end/self_employed_spec.rb
  spec/end_to_end/with_partner_spec.rb
  spec/end_to_end/without_partner_spec.rb
Labels: Approved

#790 EL-998: CW form switch-on - No merge before 10 July
  app/models/change_logs.rb
  app/views/change_logs/history_texts/_cw_forms.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved, UAT

#794 EL-884: Add help page for public beta
  app/controllers/helps_controller.rb
  app/lib/feature_flags.rb
  app/views/helps/show.html.slim
  app/views/layouts/_footer.html.slim
  config/locales/en.yml
  config/routes.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved, UAT

#796 EL-1012: Make self-employment text more visible
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, Ready For Review

#797 EL-981: Add more text about valuations.
  app/views/estimate_flow/additional_property_details.html.slim
  app/views/estimate_flow/partner_additional_property_details.html.slim
  app/views/estimate_flow/property_entry.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#791 EL-1001: Update pensioner disregard name
  config/locales/en.yml
  spec/views/results_page/client_financial_content_spec.rb
  spec/views/results_page/pensioner_content_spec.rb
Labels: Approved, UAT

#805 EL-1032: Get local run coverage up to 100%
  Gemfile
  Gemfile.lock
  spec/features/help_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Approved

#803 EL-1000: Add more end-to-end specs
  spec/end_to_end/result_page_variations_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved

#806 EL-1028: Collect samples for CSP reports
  config/initializers/content_security_policy.rb
Labels: Approved

#770 EL-961 Derive feature flags from session data, then env vars
  README.md
  app/controllers/estimates_controller.rb
  app/forms/applicant_form.rb
  app/forms/partner_details_form.rb
  app/helpers/applicant_helper.rb
  app/helpers/assets_helper.rb
  app/helpers/employment_helper.rb
  app/lib/feature_flags.rb
  app/lib/steps/income_section.rb
  app/lib/steps/logic.rb
  app/lib/steps/partner_section.rb
  app/models/check.rb
  app/services/cfe/employment_income_payload_service.rb
  app/services/error_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_employment.html.slim
  app/views/estimate_flow/forms/_income.html.slim
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimates/_evidence.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  app/views/feature_flags/index.html.slim
  app/views/layouts/_footer.html.slim
  app/views/start/index.html.slim
  spec/features/feature_flags_spec.rb
  spec/models/feature_flags_spec.rb
  spec/services/error_service_spec.rb
Labels: Approved, UAT

#793 EL-1009: Express benefits as regular transactions
  app/services/cfe/benefits_payload_service.rb
  app/services/cfe/partner_payload_service.rb
  app/services/cfe/regular_transactions_payload_service.rb
  app/services/cfe_param_builders/partner_regular_transactions.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/cfe_param_builders/state_benefits.rb
  app/services/cfe_service.rb
  spec/end_to_end/with_partner_spec.rb
  spec/end_to_end/without_partner_spec.rb
  spec/services/cfe/benefits_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
  spec/services/cfe_service_spec.rb
Labels: Approved, UAT

#812 EL-1036 - Use Jira/CircleCI integration
  .circleci/config.yml
  README.md
Labels: Approved

#809 EL-1027: Remove special applicants feature flag
  app/helpers/applicant_helper.rb
  app/helpers/assets_helper.rb
  app/helpers/employment_helper.rb
  app/lib/feature_flags.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_employment.html.slim
  app/views/estimate_flow/forms/_income.html.slim
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimates/_evidence.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/forms/applicant_form_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/employment_form_spec.rb
  spec/forms/partner_assets_form_spec.rb
  spec/forms/partner_employment_form_spec.rb
  spec/rails_helper.rb
  spec/views/results_page/types_of_evidence_spec.rb
Labels: Approved, UAT

#807 EL-1030: The liveness check checks the database is accessible
  app/controllers/status_controller.rb
  app/services/health_check_service.rb
  spec/requests/statuses_controller_spec.rb
Labels: Approved, UAT

#817 EL-1047: CSP-friendly approach to JS back button
  app/helpers/application_helper.rb
  app/javascript/application.js
Labels: Approved, UAT

#822 EL-1021: Tag GH team to allow log review
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#824 EL-1022: Redirect to primary host system
  app/controllers/application_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/start_controller.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/controllers/start_controller_spec.rb
Labels: Approved, UAT

#825 EL-1033: new staging domain
  bin/deploy
  helm_deploy/laa-estimate-eligibility/templates/NOTES.txt
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#815 EL-1034: Track referrers
  app/controllers/start_controller.rb
  spec/features/referrers_spec.rb
Labels: Approved, UAT

#827 EL-1035: Add MTR phase 1 banner and changelog
  app/models/change_logs.rb
  app/views/change_logs/banner_texts/_mtr_phase_1.html.slim
  app/views/change_logs/history_texts/_mtr_phase_1.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#831 EL-1020: Update readme to highlight CFE-Civil
  README.md
Labels: Approved

#830 EL-1013: Update under-18 content
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#826 EL-1037: Add new CW1 and 2 mapping for MTR phase 1
  app/lib/controlled_work_mappings/cw1_and_2_mtr_phase_1.yml
  app/services/controlled_work_document_population_service.rb
  lib/cw1-and-2-form-mtr-phase-1.pdf
  spec/forms/controlled_work_document_selection_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#835 EL-1040: Update accessibility statement for clarity
  app/views/accessibilities/show.html.slim
  config/locales/en.yml
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#813 EL-978: Add another additional property
  app/controllers/flow/handler.rb
  app/forms/additional_property_details_form.rb
  app/forms/client_assets_form.rb
  app/forms/client_property_entry_form.rb
  app/forms/concerns/add_anotherable.rb
  app/forms/income_form.rb
  app/forms/partner_additional_property_details_form.rb
  app/forms/partner_income_form.rb
  app/forms/property_entry_form.rb
  app/forms/vehicles_details_form.rb
  app/javascript/add-another.js
  app/lib/check_answers_fields.yml
  app/models/additional_property_model.rb
  app/models/calculation_result.rb
  app/models/check.rb
  app/models/controlled_work_document_content.rb
  app/models/disputed_property_status.rb
  app/services/cfe/assets_payload_service.rb
  app/services/cfe/partner_payload_service.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/_additional_property_section.html.slim
  app/views/estimate_flow/additional_property_details.html.slim
  app/views/estimate_flow/forms/_additional_property_details.html.slim
  app/views/estimate_flow/partner_additional_property_details.html.slim
  app/views/estimates/_capital_table.html.slim
  app/views/estimates/_property_table.html.slim
  app/views/shared/add_another/_percentage_field.html.slim
  config/locales/en.yml
  spec/end_to_end/with_partner_spec.rb
  spec/factories/session.rb
  spec/forms/additional_property_details_form_spec.rb
  spec/forms/partner_additional_property_details_form_spec.rb
  spec/forms/property_entry_form_spec.rb
  spec/models/calculation_result_spec.rb
  spec/models/check_spec.rb
  spec/models/controlled_work_document_content_spec.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/property_spec.rb
  spec/views/check_answers_page/partner_content/property_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
  spec/views/results_page/partially_owned_property_content_spec.rb
  spec/views/results_page/partner_financial_content_spec.rb
Labels: Approved, UAT

#837 Fix nbsp issue
  app/views/shared/_disregarded_benefits_details.html.slim
  config/locales/en.yml
Labels: Approved

#828 EL-1038: new CW2
  app/lib/controlled_work_mappings/cw2_mtr_phase_1.yml
  app/services/controlled_work_document_population_service.rb
  lib/cw2imm-form-mtr-phase-1.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#829 EL-1042: new civmeans7
  app/lib/controlled_work_mappings/civ_means_7_mtr_phase_1.yml
  app/services/controlled_work_document_population_service.rb
  lib/civ-means-7-form-mtr-phase-1.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#832 EL-1016: New CW1 form
  app/lib/controlled_work_mappings/cw1_mtr_phase_1.yml
  app/models/controlled_work_document_content.rb
  app/services/controlled_work_document_population_service.rb
  lib/cw1-form-mtr-phase-1.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#834 EL-1051 show production specific robots.txt file
  app/controllers/robots_controller.rb
  app/lib/feature_flags.rb
  app/views/layouts/application.html.slim
  app/views/robots/robots_allow.text
  app/views/robots/robots_disallow.text
  config/routes.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/features/robots_spec.rb
  spec/rails_helper.rb
Labels: Approved, UAT

#836 EL-1053: Only show childcare costs field if eligible for childcare costs
  README.md
  app/forms/outgoings_form.rb
  app/lib/check_answers_fields.yml
  app/models/calculation_result.rb
  app/models/check.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/childcare_eligibility_service.rb
  app/views/estimate_flow/forms/_outgoings.html.slim
  config/locales/en.yml
  spec/end_to_end/result_page_variations_spec.rb
  spec/forms/outgoings_form_spec.rb
  spec/forms/partner_outgoings_form_spec.rb
  spec/services/childcare_eligibility_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/outgoings_spec.rb
  spec/views/check_answers_page/partner_content/outgoings_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
  spec/views/results_page/partner_financial_content_spec.rb
Labels: Approved, UAT

#838 EL-1055: Move outgoings to client table when no partner
  app/models/calculation_result.rb
  app/views/estimates/_outgoings_table.html.slim
  config/locales/en.yml
  spec/end_to_end/self_employed_spec.rb
  spec/end_to_end/without_partner_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
Labels: Approved, UAT

#787 EL-985: Information not announced and not focusable on iOS
  README.md
  app/assets/stylesheets/print.scss
  app/controllers/estimates_controller.rb
  app/helpers/results_helper.rb
  app/services/pdf_service.rb
  app/views/estimates/_asylum_support_certificated_eligible.html.slim
  app/views/estimates/_asylum_support_controlled_eligible.html.slim
  app/views/estimates/_capital_table.html.slim
  app/views/estimates/_certificated_contribution_required.html.slim
  app/views/estimates/_certificated_eligible.html.slim
  app/views/estimates/_certificated_ineligible.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/estimates/_controlled_eligible.html.slim
  app/views/estimates/_controlled_ineligible.html.slim
  app/views/estimates/_controlled_work_next_steps.html.slim
  app/views/estimates/_disposable_capital_table.html.slim
  app/views/estimates/_evidence.html.slim
  app/views/estimates/_income_row.html.slim
  app/views/estimates/_income_table.html.slim
  app/views/estimates/_ineligible_explanation.html.slim
  app/views/estimates/_outgoings_row.html.slim
  app/views/estimates/_outgoings_table.html.slim
  app/views/estimates/_property_table.html.slim
  app/views/estimates/print.html.slim
  app/views/shared/_heading.html.slim
  spec/features/downloads_spec.rb
Labels: Approved, UAT

#833 EL-1039: New CW5
  app/lib/controlled_work_mappings/cw5_mtr_phase_1.yml
  app/models/controlled_work_document_content.rb
  app/services/controlled_work_document_population_service.rb
  lib/cw5-form-mtr-phase-1.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#844 EL-1057: Switch on self-employed
  app/models/change_logs.rb
  app/views/change_logs/history_texts/_self_employed.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved, UAT

#839 EL-1019 add new hints for all levels of help
  app/views/estimate_flow/forms/_assets.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#795 EL-986 make pdf titles single blocks
  app/assets/stylesheets/print.scss
  app/services/pdf_service.rb
  app/views/estimates/print.html.slim
Labels: Approved

#845 EL-1044: accurate certificated legislation content
  app/views/estimates/_legislation_table.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#849 EL-1061: compliance badge
  README.md
Labels: Approved

#853 Remove redundant webdrivers gem
  Gemfile
  Gemfile.lock
Labels: Approved

#852 EL-1054: Add new stats for key dashboard
  app/services/metrics/for_key_metric_dashboard_service.rb
  app/services/metrics/for_user_journey_dashboard_service.rb
  app/services/metrics_service.rb
  spec/services/metrics/for_key_metric_dashboard_service_spec.rb
  spec/services/metrics/for_user_journey_dashboard_service_spec.rb
  spec/services/metrics_service_spec.rb
Labels: Approved

#843 EL-1048: Refactor check answer screen to use cards
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/change-links.scss
  app/assets/stylesheets/check-answers.scss
  app/controllers/check_answers_controller.rb
  app/controllers/estimates_controller.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/helper.rb
  app/models/disputed_property_status.rb
  app/presenters/check_answers_presenter.rb
  app/services/check_answers/section_id_finder.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/_additional_property_section.html.slim
  app/views/estimate_flow/_bank_account_section.html.slim
  app/views/estimate_flow/_benefit_section.html.slim
  app/views/estimate_flow/_income_section.html.slim
  app/views/estimate_flow/_vehicle_section.html.slim
  app/views/estimates/_check_answer.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/estimates/_money_and_frequency_check_answer.slim
  app/views/estimates/_money_check_answer.html.slim
  app/views/estimates/check_answers.html.slim
  config/locales/en.yml
  spec/features/instant_sessions_spec.rb
  spec/flows/check_answers_flow_spec.rb
  spec/services/check_answers/section_id_finder_spec.rb
  spec/support/view_helpers.rb
  spec/views/check_answers_page/client_content/assets_spec.rb
  spec/views/check_answers_page/client_content/dependants_spec.rb
  spec/views/check_answers_page/client_content/employment_spec.rb
  spec/views/check_answers_page/client_content/housing_benefit_spec.rb
  spec/views/check_answers_page/client_content/other_benefits_spec.rb
  spec/views/check_answers_page/client_content/other_income_spec.rb
  spec/views/check_answers_page/client_content/outgoings_spec.rb
  spec/views/check_answers_page/client_content/property_spec.rb
  spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
  spec/views/check_answers_page/client_content/special_client_types/passported_client_spec.rb
  spec/views/check_answers_page/level_of_help_sidebar_content_spec.rb
  spec/views/check_answers_page/partner_content/assets_spec.rb
  spec/views/check_answers_page/partner_content/employment_spec.rb
  spec/views/check_answers_page/partner_content/other_benefits_spec.rb
  spec/views/check_answers_page/partner_content/other_income_spec.rb
  spec/views/check_answers_page/partner_content/outgoings_spec.rb
  spec/views/check_answers_page/partner_content/property_spec.rb
Labels: Approved, UAT

#848 EL-1059: Remove CW form feature flag
  app/lib/feature_flags.rb
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/features/downloads_spec.rb
  spec/flows/controlled_work_documents_spec.rb
  spec/rails_helper.rb
  spec/views/results_page/cw_forms_content_spec.rb
Labels: Approved

#846 EL-1014: LC Guidance Links - MTR Phase 1
  app/helpers/applicant_helper.rb
  app/helpers/assets_helper.rb
  app/helpers/asylum_support_helper.rb
  app/helpers/dependants_helper.rb
  app/helpers/employment_helper.rb
  app/helpers/housing_costs_helper.rb
  app/helpers/matter_type_helper.rb
  app/helpers/outgoings_helper.rb
  app/helpers/property_helper.rb
  app/helpers/vehicle_helper.rb
  app/services/guidance_link_service.rb
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/immigration_or_asylum.html.slim
  app/views/estimate_flow/immigration_or_asylum_type.html.slim
  app/views/estimate_flow/level_of_help.html.slim
  app/views/estimate_flow/matter_type.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimates/_legislation_table.html.slim
  app/views/estimates/_limits_table.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  app/views/shared/_disregarded_benefits_sidebar.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  spec/controllers/accessibilities_controller_spec.rb
  spec/controllers/privacies_controller_spec.rb
  spec/services/guidance_link_service_spec.rb
Labels: Approved, UAT

#859 EL-1063: MTR content and banner updates
  app/views/change_logs/banner_texts/_mtr_phase_1.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT
