Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-12, with the labels that each got.

#1150 EL-1270: Switch on Welsh CW forms in production
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Approved

#1153 EL-1289: Additional property mortgage validation
  app/models/additional_property_model.rb
  spec/system/add_another_spec.rb
Labels: Approved, UAT

#1155 EL-1290 speed up testing
  spec/system/accessibility_spec.rb
  spec/system/add_another_spec.rb
  spec/system/feedback_spec.rb
Labels: Approved

#1163 Add asylum support e2e spec
  spec/end_to_end/asylum_support_spec.rb
Labels: Approved

#1157 EL-1300: Instant downloads mobile safari error
  app/javascript/instant-download.js
Labels: Approved, UAT

#1160 EL-1294 add metabase
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-deployment.yaml
  helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-service.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
Labels: Approved

#1166 EL-1294 Bugfix: rename to reduce character count
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-service.yaml
Labels: Ready For Review

#1165 EL-1234: Add new text to mortgage page
  app/views/question_flow/mortgage_or_loan_payment.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1167 EL-1294 turn metabase on in production
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
Labels: Ready For Review

#1162 EL-1301: Remove end of journey feature flag
  app/controllers/controlled_work_document_selections_controller.rb
  app/controllers/results_controller.rb
  app/lib/feature_flags.rb
  app/views/controlled_work_document_selections/new.html.slim
  app/views/results/_asylum_support_controlled_eligible.html.slim
  app/views/results/_controlled_eligible.html.slim
  app/views/results/_controlled_work_next_steps.html.slim
  app/views/results/download.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/flows/controlled_work_documents_spec.rb
  spec/forms/controlled_work_document_selection_spec.rb
  spec/rails_helper.rb
  spec/system/feedback_spec.rb
  spec/views/results_page/asylum_and_immigration_content_spec.rb
  spec/views/results_page/cw_forms_content_spec.rb
Labels: Approved

#1158 EL-1297: Store session data for later analysis
  app/models/completed_user_journey.rb
  app/services/journey_logger_service.rb
  db/migrate/20231206090719_add_session_to_completed_user_journeys.rb
  db/schema.rb
  spec/services/journey_logger_service_spec.rb
Labels: Approved, UAT

#1168 EL-1306: Add content about cohabiting
  app/views/question_flow/housing_costs.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1172 EL-1288: Means aggregation
  app/controllers/flow/handler.rb
  app/forms/how_to_aggregate_form.rb
  app/lib/steps/case_details_section.rb
  app/services/external_link_service.rb
  app/views/question_flow/how_to_aggregate.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  spec/flows/under_eighteen_flow_spec.rb
  spec/rails_helper.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#1161 EL-1255: Under-18 results
  app/lib/steps/logic.rb
  app/models/calculation_result.rb
  app/models/check.rb
  app/services/cfe/applicant_payload_service.rb
  app/services/cfe/assessment_payload_service.rb
  app/services/cfe/proceedings_payload_service.rb
  app/views/checks/_check_answers_table.html.slim
  app/views/results/_result_panel_content.html.slim
  app/views/results/_under_eighteen.html.slim
  app/views/results/_under_eighteen_next_steps.html.slim
  app/views/results/download.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
  spec/end_to_end/asylum_support_spec.rb
  spec/end_to_end/passporting_spec.rb
  spec/end_to_end/under_eighteen_spec.rb
  spec/end_to_end/without_partner_spec.rb
  spec/services/cfe/applicant_payload_service_spec.rb
  spec/views/results_page/under_eighteen_content_spec.rb
Labels: Approved, UAT

#1164 EL-1302: Remove Welsh CW form feature flag
  app/lib/feature_flags.rb
  app/models/controlled_work_document_selection.rb
  app/views/controlled_work_document_selections/new.html.slim
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/flows/controlled_work_documents_spec.rb
  spec/forms/controlled_work_document_selection_spec.rb
  spec/rails_helper.rb
Labels: Approved, UAT

#1177 BUG: When forms are reordered, property isn't skipped when means test should be skipped
  app/lib/steps/outgoings_section.rb
Labels: Approved

#1178 EL-1311: Skip irrelevant CW fields when u18
  app/models/controlled_work_document_content.rb
  app/views/question_flow/how_to_aggregate.html.slim
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1180 Enable u18 on staging and production
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Approved

#1173 EL-1304: Conditional reveals on other income
  app/forms/other_income_form.rb
  app/lib/check_answers_fields.yml
  app/lib/check_answers_fields_old_flow.yml
  app/lib/feature_flags.rb
  app/models/check.rb
  app/services/cfe_param_builders/irregular_income.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/check_answers/section_lister_service.rb
  app/services/childcare_eligibility_service.rb
  app/views/checks/_check_answers_table.html.slim
  app/views/checks/_money_and_frequency_check_answer.slim
  app/views/checks/_money_check_answer.html.slim
  app/views/question_flow/forms/_other_income.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/end_to_end/other_income_spec.rb
  spec/forms/other_income_form_spec.rb
  spec/rails_helper.rb
  spec/services/childcare_eligibility_service_spec.rb
  spec/views/check_answers_page/client_content/outgoings_spec.rb
  spec/views/check_answers_page/partner_content/outgoings_spec.rb
Labels: Approved, UAT

#1181 EL-980: Certificated Results page - contributions content update
  config/locales/en.yml
  spec/end_to_end/result_page_variations_spec.rb
  spec/end_to_end/without_partner_spec.rb
Labels: Approved, UAT

#1176 EL-1305: Conditional reveals on outgoings pages
  app/forms/other_income_form.rb
  app/forms/outgoings_form.rb
  app/lib/check_answers_fields.yml
  app/lib/check_answers_fields_old_flow.yml
  app/services/cfe_param_builders/irregular_income.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/check_answers/section_lister_service.rb
  app/services/childcare_eligibility_service.rb
  app/views/question_flow/forms/_housing_benefit.html.slim
  app/views/question_flow/forms/_housing_benefit_details.html.slim
  app/views/question_flow/forms/_other_income.html.slim
  app/views/question_flow/forms/_outgoings.html.slim
  config/locales/en.yml
  spec/end_to_end/other_income_spec.rb
  spec/forms/other_income_form_spec.rb
  spec/forms/outgoings_form_spec.rb
  spec/services/childcare_eligibility_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/outgoings_spec.rb
  spec/views/check_answers_page/partner_content/outgoings_spec.rb
Labels: Approved, UAT
