Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-11, with the labels that each got.

#1037 EL-1188: Welsh CW2 form
  app/lib/controlled_work_mappings/cw2_welsh.yml
  app/services/controlled_work_document_population_service.rb
  lib/cw2imm-form-welsh.pdf
  spec/forms/controlled_work_document_selection_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1039 EL-1190: Welsh CW5 form
  app/lib/controlled_work_mappings/cw5_welsh.yml
  app/services/controlled_work_document_population_service.rb
  lib/cw5-form-welsh.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1038 EL-1189: Welsh CW1&2 form
  app/lib/controlled_work_mappings/cw1_and_2_welsh.yml
  app/services/controlled_work_document_population_service.rb
  lib/cw1-and-2-form-welsh.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1040 EL-1191: Welsh CW7 form
  app/lib/controlled_work_mappings/civ_means_7_welsh.yml
  app/services/controlled_work_document_population_service.rb
  lib/civ-means-7-form-welsh.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1053 EL-1241: Delete dependabot releases when PRs combined
  .github/actions/delete-uat-release/action.yml
  .github/workflows/combine-prs.yml
Labels: Approved

#1063 EL-1238 Part A: turn on UAT maintenance mode
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Ready For Review

#1064 EL-1238 Part B: Update hostnames and values
  .circleci/config.yml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Ready For Review

#1065 EL-1238 Part C: switch off maintenace mode
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Ready For Review

#1061 EL-1237: Auto-restore a broken database connection
  app/controllers/application_controller.rb
  spec/requests/statuses_controller_spec.rb
Labels: Approved, UAT

#1052 EL-1236: pending answers in change answer loops
  app/controllers/change_answers_controller.rb
  app/helpers/application_helper.rb
  app/views/checks/_check_answers_table.html.slim
  config/routes.rb
  spec/flows/change_answers_flow_spec.rb
Labels: Approved, UAT

#1076 EL-1242: Step two: swap hosts over
  .circleci/config.yml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Ready For Review

#1077 EL-1242: Step three: disable maintenance mode
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Ready For Review

#1083 EL-1267: End of Journey - feature flag
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/rails_helper.rb
Labels: Approved, UAT

#1081 EL-1259: Incorrect check answers text
  config/locales/en.yml
  spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
Labels: Approved, UAT

#1079 EL-1244: Missing disputed asset tags
  app/lib/check_answers_fields.yml
  spec/views/check_answers_page/client_content/assets_spec.rb
Labels: Approved, UAT

#1080 EL-1247: Add feature flag for under-18 questions
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/rails_helper.rb
Labels: Approved

#1087 EL-1257: Improve instant sessions and add f-flagged CW form changes
  app/controllers/application_controller.rb
  app/controllers/checks_controller.rb
  app/controllers/controlled_work_document_selections_controller.rb
  app/controllers/instant_sessions_controller.rb
  app/lib/feature_flags.rb
  app/views/controlled_work_document_selections/new.html.slim
  config/locales/en.yml
  spec/forms/controlled_work_document_selection_spec.rb
  spec/rails_helper.rb
Labels: Approved, UAT

#1096 EL-1272: Add dedicated maintenance mode screen
  app/controllers/application_controller.rb
  public/maintenance.html
  spec/features/maintenance_mode_spec.rb
Labels: Approved, UAT

#1097 EL-1243 part 1: Switch on maintenance mode
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
Labels: Approved

#1098 EL-1243 part 2: update config
  .circleci/config.yml
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
Labels: Approved

#1099 EL-1243 part 3: Exit maintenance mode in new namespace
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
Labels: Approved

#1103 Remove deployment to old NS from circle config
  .circleci/config.yml
Labels: Approved

#1104 EL-1275: Remove content from results PDF, controlled & eligible
  app/controllers/results_controller.rb
  app/helpers/results_helper.rb
  app/views/estimates/_controlled_work_next_steps.html.slim
  app/views/results/_controlled_work_next_steps.html.slim
  app/views/results/show.html.slim
  spec/system/feedback_spec.rb
Labels: Approved, UAT

#1100 EL-1258: End of journey
  app/controllers/checks_controller.rb
  app/controllers/controlled_work_document_selections_controller.rb
  app/javascript/application.js
  app/javascript/instant-download.js
  app/models/controlled_work_document_selection.rb
  app/views/checks/end_of_journey.html.slim
  app/views/controlled_work_document_selections/new.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/redirects_spec.rb
  spec/flows/controlled_work_documents_spec.rb
Labels: Approved, UAT

#1101 EL-1263: Satisfaction comments
  app/controllers/feedbacks_controller.rb
  app/javascript/feedback.js
  app/models/satisfaction_feedback.rb
  app/views/layouts/_feedback.html.slim
  config/locales/en.yml
  config/routes.rb
  db/migrate/20231115112811_add_comment_to_satisfaction_feedback.rb
  db/schema.rb
  spec/factories/satisfaction_feedback.rb
  spec/requests/feedbacks_spec.rb
  spec/system/feedback_spec.rb
Labels: Approved, UAT

#1105 EL-1262: AWS Secret manager
  README.md
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
Labels: Approved

#1106 EL-1223: Update all documentation and references to old names
  .circleci/config.yml
  .github/CODEOWNERS
  README.md
  bin/deploy
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  infrastructure/laa-check-client-qualifies-uat/ingress-dashboard.yaml
  infrastructure/laa-check-client-qualifies-uat/permanent-redirects.yaml
  infrastructure/laa-check-client-qualifies-uat/pods-dashboard.yaml
  lib/scripts/migrate-rds.sh
  lib/scripts/migrate-redis.sh
  package.json
Labels: Approved

#1116 EL-1231: Remove deprecation warning
  config/initializers/devise.rb
Labels: Ready For Review

#1119 Remove attempt to interact with old UAT namespace
  .github/workflows/combine-prs.yml
  .github/workflows/delete_uat_release.yml
Labels: Approved

#1123 EL-1279: Tweak certificated results wording
  app/views/results/download.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1115 EL-1248: client age screen
  app/controllers/checks_controller.rb
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/client_age_form.rb
  app/helpers/applicant_helper.rb
  app/helpers/client_age_helper.rb
  app/helpers/forms_helper.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/case_details_section.rb
  app/lib/steps/helper.rb
  app/models/check.rb
  app/models/completed_user_journey.rb
  app/services/cfe/applicant_payload_service.rb
  app/services/external_link_service.rb
  app/services/journey_logger_service.rb
  app/views/question_flow/applicant.html.slim
  app/views/question_flow/client_age.html.slim
  config/locales/en.yml
  db/migrate/20231121163655_add_client_age_to_completed_user_journeys.rb
  db/schema.rb
  spec/flows/under_eighteen_flow_spec.rb
  spec/forms/applicant_form_spec.rb
  spec/forms/client_age_form_spec.rb
  spec/services/cfe/applicant_payload_service_spec.rb
  spec/services/journey_logger_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/client_details_spec.rb
Labels: Approved, UAT

#1124 EL-1281: CW forms when asylum supported
  app/models/controlled_work_document_selection.rb
  app/views/controlled_work_document_selections/new.html.slim
  spec/forms/controlled_work_document_selection_spec.rb
Labels: Approved, UAT

#1117 EL-1246: Removal of Under 18 content from CCQ start page.
  app/views/start/index.html.slim
Labels: Approved, UAT

#1122 EL-1280: Controlled work check with asylum support - results page changes
  app/controllers/results_controller.rb
  app/views/results/_asylum_support_controlled_eligible.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1120 EL-1251: Regular income screen
  app/controllers/flow/handler.rb
  app/forms/regular_income_form.rb
  app/lib/steps/case_details_section.rb
  app/lib/steps/logic.rb
  app/services/external_link_service.rb
  app/views/question_flow/regular_income.html.slim
  config/locales/en.yml
  spec/flows/under_eighteen_flow_spec.rb
  spec/forms/regular_income_form_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#1126 EL-1282: Mortgage not showing on CW forms
  app/models/concerns/property_summarisable.rb
  spec/models/controlled_work_document_content_spec.rb
Labels: Approved, UAT

#1121 EL-1252: U18 assets
  app/controllers/flow/handler.rb
  app/forms/controlled_legal_representation_form.rb
  app/forms/under_eighteen_assets_form.rb
  app/helpers/under_18_clr_helper.rb
  app/lib/steps/applicant_details_section.rb
  app/lib/steps/assets_and_vehicles_section.rb
  app/lib/steps/case_details_section.rb
  app/lib/steps/income_section.rb
  app/lib/steps/logic.rb
  app/lib/steps/outgoings_section.rb
  app/lib/steps/partner_section.rb
  app/lib/steps/property_section.rb
  app/models/check.rb
  app/services/external_link_service.rb
  app/views/question_flow/under_18_clr.html.slim
  app/views/question_flow/under_eighteen_assets.html.slim
  config/locales/en.yml
  spec/flows/under_eighteen_flow_spec.rb
  spec/forms/controlled_legal_representation_form_spec.rb
  spec/forms/under_eighteen_assets_form_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#1127 EL-1249 under18 CLR question
  app/services/external_link_service.rb
  app/views/question_flow/under_18_clr.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1129 EL-1283: Enable end-of-journey flag
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Approved

#1128 EL-1254: U18 check answers
  app/assets/stylesheets/check-answers.scss
  app/lib/check_answers_fields.yml
  app/services/check_answers/section_lister_service.rb
  app/views/checks/_check_answer.html.slim
  app/views/checks/_check_answers_table.html.slim
  config/locales/en.yml
  spec/factories/session.rb
  spec/views/check_answers_page/client_content/special_client_types/under_eighteen_client_spec.rb
Labels: Approved, UAT

#1138 EL-1284: Change 'means assessment' to 'full means test'
  config/locales/en.yml
Labels: Approved, UAT

#1139 EL-1285 Update method to account for new CFE result type
  app/models/calculation_result.rb
  spec/views/results_page/eligibility_content_spec.rb
Labels: Approved, UAT

#1141 EL-1286: CW file names
  app/controllers/controlled_work_document_selections_controller.rb
  app/controllers/results_controller.rb
  app/helpers/application_helper.rb
  config/locales/en.yml
  spec/flows/controlled_work_documents_spec.rb
Labels: Approved, UAT

#1137 EL-1277: Under 18s - CLR - Select CW form - 2nd Attempt
  app/models/controlled_work_document_selection.rb
  spec/forms/controlled_work_document_selection_spec.rb
Labels: Approved, UAT

#1142 EL-1278: Update to view and added in some check methods.
  app/models/check.rb
  app/views/checks/end_of_journey.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1130 EL-1266: U18 Welsh CW
  app/lib/controlled_work_mappings/civ_means_7_welsh.yml
  app/lib/controlled_work_mappings/cw1_and_2_welsh.yml
  app/lib/controlled_work_mappings/cw1_welsh.yml
  app/lib/controlled_work_mappings/cw2_welsh.yml
  app/lib/controlled_work_mappings/cw5_welsh.yml
  app/lib/steps/logic.rb
  app/models/check.rb
  lib/civ-means-7-form-welsh.pdf
  lib/cw5-form-welsh.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#1143 EL-1111: Certificated/ineligible results text
  app/views/results/_certificated_ineligible.html.slim
  app/views/results/_certificated_next_steps.html.slim
  app/views/results/download.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
  spec/views/results_page/eligibility_content_spec.rb
Labels: Approved, UAT

#1146 EL-1287a: Rubocop workflow can be "dispatched" via API
  .github/workflows/rubocop.yml
Labels: Approved

#1144 EL-1287: Enable Rubocop to be a required check
  .github/dependabot.yml
  .github/workflows/combine-prs.yml
  .github/workflows/rubocop.yml
Labels: Approved
