Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-06, with the labels that each got.

#704 EL-932: Controlled work, results page - content update
  app/views/estimates/_controlled_work_next_steps.html.slim
  app/views/estimates/_evidence.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#707 EL-938 add flag check for SPAG content on assets page
  app/views/estimate_flow/household_flow/_property.html.slim
  app/views/estimate_flow/household_flow/forms/_assets.html.slim
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/forms/assets_form_spec.rb
Labels: Approved, UAT

#710 EL-948: Enabling UAT feature flags
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Ready For Review

#708 EL-940 turn on household flow in production
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved

#716 EL-958 add self employed feature flag
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#725 EL-963: Prevent nil regular transaction frequencies
  app/services/cfe_param_builders/household_flow_regular_transactions.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
Labels: Approved, UAT

#717 EL-952: CW1 non-smod property bug
  app/lib/controlled_work_mappings/cw1.yml
Labels: Approved, UAT

#718 EL-954: Leave ownership percentage field blank if not calculable
  app/models/controlled_work_document_content.rb
  spec/models/controlled_work_document_content_spec.rb
Labels: Approved, UAT

#719 [EL-951] Fix typo on CIVMEANS7
  app/lib/controlled_work_mappings/civ_means_7.yml
Labels: Approved

#727 Remove old flags from specs
  spec/flows/controlled_work_documents_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
Labels: Approved

#724 EL-937 refactor passporting test
  spec/end_to_end/passporting_spec.rb
Labels: Approved

#722 EL-906 Add aria labels
  app/views/estimate_flow/forms/_other_income.html.slim
  app/views/estimate_flow/forms/_outgoings.html.slim
  app/views/estimate_flow/housing_costs.html.slim
  app/views/shared/_money_input.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#730 EL-936: Use version file to store git commit hash in cloud platform
  .dockerignore
  Dockerfile
  app/lib/cfe_connection.rb
  spec/services/cfe_connection_spec.rb
Labels: Approved, UAT

#732 EL-966: Allow zero mortgage payments
  app/forms/mortgage_or_loan_payment_form.rb
  config/locales/en.yml
  spec/forms/mortgage_or_loan_payment_form_spec.rb
Labels: Approved, UAT

#728 EL-942 Client employment status screen
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/employment_status_form.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/income_section.rb
  app/lib/steps/logic.rb
  app/models/check.rb
  app/services/check_answers/section_id_finder.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/employment_status.html.slim
  config/locales/en.yml
  spec/flows/household_flow_spec.rb
  spec/forms/applicant_form_spec.rb
  spec/forms/employment_status_form_spec.rb
  spec/services/check_answers/section_id_finder_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/employment_spec.rb
Labels: Approved, UAT

#709 EL-897: Update to 'Start page' for SAG including self employed
  app/views/start/index.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved, UAT

#729 EL-962: mortgage payments screen showing for passported clients
  app/lib/steps/property_section.rb
  spec/flows/household_flow_spec.rb
Labels: Approved, UAT

#731 EL-964: Fix minus signs on vehicle result summaries
  app/models/calculation_result.rb
  spec/views/results_page/client_financial_content_spec.rb
Labels: Approved, UAT

#745 EL-886: Fix dashboard stacking
  infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
Labels: Approved

#743 EL-949: Mental health content
  app/views/estimate_flow/level_of_help.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#744 EL-950: Level of help copy formatting
  app/views/estimate_flow/level_of_help.html.slim
Labels: Approved, UAT

#746 EL-970: DRY up Circle workflows
  .circleci/config.yml
Labels: Approved

#748 EL-969: Simplify deployment config
  .circleci/config.yml
  bin/deploy
Labels: Approved

#735 EL-953: Updated CW1 form
  app/lib/controlled_work_mappings/cw1.yml
  lib/cw1-form.pdf
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved, UAT

#742 EL-945: Partner employment status
  app/controllers/flow/handler.rb
  app/forms/partner_details_form.rb
  app/forms/partner_employment_status_form.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/logic.rb
  app/lib/steps/partner_section.rb
  app/services/check_answers/section_id_finder.rb
  app/views/estimate_flow/employment_status.html.slim
  app/views/estimate_flow/forms/_employment_status.html.slim
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimate_flow/partner_employment_status.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/flows/self_employment_flow_spec.rb
  spec/forms/partner_details_form_spec.rb
  spec/forms/partner_employment_status_form_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/partner_content/employment_spec.rb
Labels: Approved, UAT

#734 EL-923: new matter type flow
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/immigration_or_asylum_form.rb
  app/forms/immigration_or_asylum_type_form.rb
  app/forms/matter_type_form.rb
  app/helpers/build_estimates_helper.rb
  app/helpers/matter_type_helper.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/case_details_section.rb
  app/lib/steps/logic.rb
  app/models/check.rb
  app/services/cfe/proceedings_payload_service.rb
  app/services/check_answers/section_id_finder.rb
  app/services/journey_logger_service.rb
  app/services/metrics/from_completed_journeys_service.rb
  app/views/estimate_flow/immigration_or_asylum.html.slim
  app/views/estimate_flow/immigration_or_asylum_type.html.slim
  app/views/estimate_flow/matter_type.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/estimates/_limits_table.html.slim
  config/locales/en.yml
  spec/factories/api_results.rb
  spec/factories/session.rb
  spec/features/number_fields_spec.rb
  spec/flows/check_answers_flow_spec.rb
  spec/flows/controlled_work_spec.rb
  spec/forms/additional_property_details_form_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/immigration_or_asylum_form_spec.rb
  spec/forms/immigration_or_asylum_type_form_spec.rb
  spec/forms/matter_type_form_spec.rb
  spec/forms/property_entry_form_spec.rb
  spec/forms/vehicles_details_form_spec.rb
  spec/models/steps/logic_spec.rb
  spec/services/cfe/applicant_payload_service_spec.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/services/cfe/proceedings_payload_service_spec.rb
  spec/services/cfe/vehicle_payload_service_spec.rb
  spec/services/journey_logger_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
  spec/views/results_page/asylum_and_immigration_content_spec.rb
  spec/views/results_page/eligibility_content_spec.rb
  spec/views/results_page/partner_financial_content_spec.rb
Labels: Approved, UAT

#733 EL-908 add new content to results page
  app/views/estimates/_evidence.html.slim
  config/locales/en.yml
  spec/views/results_page/types_of_evidence_spec.rb
Labels: Approved, UAT

#720 EL-911: Change log update for special applicants
  app/models/change_logs.rb
  app/views/change_logs/banner_texts/_household_flow.html.slim
  app/views/change_logs/history_texts/_special_applicants.html.slim
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/partner_details.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved, UAT

#760 EL-976: Switch from mode to median
  app/services/metrics/from_analytics_service.rb
  spec/services/metrics/from_analytics_service_spec.rb
Labels: Approved

#758 EL-925: add another bank account
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/forms/base_add_another_form.rb
  app/forms/base_assets_form.rb
  app/forms/benefit_details_form.rb
  app/forms/client_assets_form.rb
  app/forms/concerns/add_anotherable.rb
  app/forms/concerns/session_persistable.rb
  app/forms/concerns/session_persistable_with_prefix.rb
  app/forms/partner_assets_form.rb
  app/forms/partner_benefit_details_form.rb
  app/forms/vehicles_details_form.rb
  app/javascript/add-another.js
  app/models/bank_account_model.rb
  app/models/check.rb
  app/models/controlled_work_document_content.rb
  app/models/disputed_property_status.rb
  app/services/cfe/assets_payload_service.rb
  app/services/cfe_param_builders/capitals.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/_bank_account_section.html.slim
  app/views/estimate_flow/_vehicle_section.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_benefit_details.html.slim
  app/views/estimate_flow/vehicles_details.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/shared/add_another/_checkbox_field.html.slim
  app/views/shared/add_another/_money_field.html.slim
  config/locales/en.yml
  spec/factories/session.rb
  spec/flows/check_answers_flow_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/partner_assets_form_spec.rb
  spec/forms/vehicles_details_form_spec.rb
  spec/models/controlled_work_document_content_spec.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
  spec/support/flow_helpers.rb
  spec/system/add_another_spec.rb
  spec/views/check_answers_page/client_content/assets_spec.rb
  spec/views/check_answers_page/partner_content/assets_spec.rb
Labels: Approved, UAT

#749 EL-967: Feature flag overrides
  README.md
  app/controllers/feature_flags_controller.rb
  app/lib/feature_flags.rb
  app/models/feature_flag_override.rb
  app/views/feature_flags/edit.html.slim
  app/views/feature_flags/index.html.slim
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230615101849_create_feature_flag_overrides.rb
  db/schema.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/features/feature_flags_spec.rb
  spec/models/feature_flags_spec.rb
Labels: Approved, UAT

#757 [EL-982] Fix change loop redirect bug
  app/forms/applicant_form.rb
  spec/flows/check_answers_flow_spec.rb
Labels: Approved

#759 EL-960: Add a content security policy
  app/views/layouts/_analytics_head.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
  config/initializers/content_security_policy.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved, UAT

#771 EL-989: Only show self-employed help on assets screen for certificated
  app/views/estimate_flow/forms/_assets.html.slim
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/forms/assets_form_spec.rb
Labels: Approved, UAT

#773 BUG: Main UAT deployments failing
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#761 EL-973: Session checking
  app/controllers/estimates_controller.rb
  app/services/cfe/applicant_payload_service.rb
  app/services/cfe/assessment_payload_service.rb
  app/services/cfe/assets_payload_service.rb
  app/services/cfe/base_service.rb
  app/services/cfe/benefits_payload_service.rb
  app/services/cfe/dependants_payload_service.rb
  app/services/cfe/employment_income_payload_service.rb
  app/services/cfe/invalid_session_error.rb
  app/services/cfe/irregular_income_payload_service.rb
  app/services/cfe/partner_payload_service.rb
  app/services/cfe/proceedings_payload_service.rb
  app/services/cfe/regular_transactions_payload_service.rb
  app/services/cfe/vehicle_payload_service.rb
  app/services/cfe_param_builders/household_flow_regular_transactions.rb
  app/services/cfe_param_builders/partner_regular_transactions.rb
  app/views/estimates/invalid_session.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/end_to_end/passporting_spec.rb
  spec/end_to_end/without_partner_spec.rb
  spec/features/invalid_session_spec.rb
  spec/services/cfe/applicant_payload_service_spec.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/services/cfe/benefits_payload_service_spec.rb
  spec/services/cfe/dependants_payload_service_spec.rb
  spec/services/cfe/employment_income_payload_service_spec.rb
  spec/services/cfe/irregular_income_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
Labels: Approved, UAT

#750 EL-943: add another income
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/summary-lists.scss
  app/controllers/flow/handler.rb
  app/forms/income_form.rb
  app/forms/partner_income_form.rb
  app/helpers/employment_helper.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/income_section.rb
  app/lib/steps/partner_section.rb
  app/models/check.rb
  app/models/income_model.rb
  app/services/cfe/applicant_payload_service.rb
  app/services/cfe/employment_income_payload_service.rb
  app/services/cfe/partner_payload_service.rb
  app/services/cfe_param_builders/employment.rb
  app/services/cfe_param_builders/employment_incomes.rb
  app/services/cfe_param_builders/self_employment.rb
  app/services/check_answers/section_id_finder.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/_benefit_section.html.slim
  app/views/estimate_flow/_income_section.html.slim
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_income.html.slim
  app/views/estimate_flow/income.html.slim
  app/views/estimate_flow/partner_income.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/shared/add_another/_radio_field.html.slim
  config/locales/en.yml
  spec/end_to_end/self_employed_spec.rb
  spec/factories/session.rb
  spec/flows/household_flow_spec.rb
  spec/flows/self_employment_flow_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/income_form_spec.rb
  spec/services/cfe/employment_income_payload_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/employment_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
  spec/views/results_page/partner_financial_content_spec.rb
Labels: Approved, UAT

#751 EL-947: partner income scree
  app/forms/partner_income_form.rb
  app/lib/check_answers_fields.yml
  app/lib/steps/partner_section.rb
  app/models/check.rb
  app/models/income_model.rb
  app/services/cfe/partner_payload_service.rb
  app/services/cfe_param_builders/capitals.rb
  app/services/cfe_param_builders/irregular_income.rb
  app/services/check_answers/section_lister_service.rb
  app/views/estimate_flow/_income_section.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_income.html.slim
  config/locales/en.yml
  spec/end_to_end/self_employed_spec.rb
  spec/factories/session.rb
  spec/flows/self_employment_flow_spec.rb
  spec/forms/partner_assets_form_spec.rb
  spec/forms/partner_income_form_spec.rb
  spec/services/cfe/employment_income_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#774 EL-996: Print buttons not working
  app/javascript/application.js
  app/views/estimates/print.html.slim
Labels: Approved, UAT
