Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-01, with the labels that each got.

#325 EL-591: Subheader font
  app/views/estimate_flow/partner_property.html.slim
  app/views/estimate_flow/partner_vehicle.html.slim
Labels: Approved, UAT

#327 EL-580 hide partner employment question when client is passported
  app/forms/partner_details_form.rb
  app/views/estimate_flow/partner_details.html.slim
  spec/features/applicant_page_spec.rb
  spec/features/property_page_spec.rb
Labels: Approved

#313 Tidy PR template
  .github/pull_request_template.md
Labels: Approved

#332 EL-603 rotate git crypt key
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#326 EL-570: Add cost of living wording
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_add_benefit_form.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_other_income.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/partner_benefits/new.html.slim
  app/views/shared/_cost_of_living.html.slim
  app/views/shared/_disregarded_benefits.html.slim
  config/locales/en.yml
  spec/features/partner_benefits_spec.rb
Labels: Approved, UAT

#330 EL-599: Update partner salary and benefits
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_add_benefit_form.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/forms/_employment.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/partner_benefits/edit.html.slim
  app/views/partner_benefits/new.html.slim
  app/views/shared/_disregarded_benefits_details.html.slim
  app/views/shared/_disregarded_benefits_sidebar.html.slim
  app/views/shared/_money_input.html.slim
  config/locales/en.yml
  spec/features/benefits_spec.rb
  spec/features/housing_benefit_page_spec.rb
  spec/features/partner_dependants_pages_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/partner_housing_benefit_pages_spec.rb
Labels: Approved, UAT

#334 EL-604: Scheduled changes
  README.md
  app/forms/applicant_form.rb
  app/lib/feature_flags.rb
  app/services/check_answers/applicant_section.rb
  app/services/submit_partner_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_other_income.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/shared/_cost_of_living.html.slim
  app/views/shared/_disregarded_benefits_details.html.slim
  app/views/start/index.html.slim
  config/initializers/flipper.rb
  config/locales/en.yml
  spec/lib/feature_flags_spec.rb
  spec/support/navigation_helpers.rb
Labels: Approved

#331 EL-600: Other income, outgoings and check answers
  app/views/estimate_flow/partner_assets.html.slim
  app/views/estimate_flow/partner_employment.html.slim
  config/locales/en.yml
  spec/features/check_answers_page_spec.rb
Labels: Approved, UAT

#329 EL-598: Assets, outgoings and dependants pages
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/forms/_dependant_details.html.slim
  app/views/estimate_flow/partner_dependant_details.html.slim
  app/views/estimate_flow/partner_details.html.slim
  config/locales/en.yml
  spec/features/assets_page_spec.rb
  spec/features/change_employment_type_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/other_income_page_spec.rb
  spec/features/outgoings_page_spec.rb
  spec/features/partner_dependants_pages_spec.rb
  spec/features/partner_employment_page_spec.rb
  spec/features/vehicle_page_spec.rb
Labels: Approved, UAT

#342 Parallelise ECR push step to save 1min 30sec during deployment testing
  .circleci/config.yml
Labels: Approved

#336 EL-596 property content
  config/locales/en.yml
  spec/features/property_page_spec.rb
Labels: Approved, UAT

#333 EL-601: Missing fields on check answers
  app/lib/check_answers_fields.yml
  app/services/check_answers/applicant_section.rb
  config/locales/en.yml
Labels: Approved, UAT

#328 EL-597: Content changes for vehicle pages
  config/locales/en.yml
Labels: Approved, UAT

#345 EL-611: Use CFE UAT on CCQ UAT
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#311 EL-537: Add chart of error rate
  infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
Labels: Ready For Review

#297 EL-558 re-use faraday connection for every CFE request
  Gemfile
  Gemfile.lock
  app/lib/cfe_connection.rb
  app/services/base_cfe_service.rb
  app/services/cfe_service.rb
  spec/services/submit_benefits_service_spec.rb
  spec/services/submit_dependants_service_spec.rb
  spec/services/submit_partner_service_spec.rb
  spec/services/submit_regular_transactions_service_spec.rb
Labels: Approved, UAT

#348 EL-606: Update accessibility statement
  app/views/accessibilities/_list.html.slim
  app/views/accessibilities/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#353 EL-612: Route production CFE requests internally
  helm_deploy/laa-estimate-eligibility/values-production.yaml
Labels: Approved

#344 EL-605 Partner Property content
  config/locales/en.yml
Labels: Approved, UAT

#346 EL-595 content changes for applicant details and dependants
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/forms/_dependant_details.html.slim
  config/locales/en.yml
  spec/features/benefits_spec.rb
  spec/features/other_income_page_spec.rb
Labels: Approved, UAT

#361 EL-621: Income and outgoings tables
  app/views/estimates/_income_row.html.slim
  app/views/estimates/_income_table.html.slim
  app/views/estimates/_outgoings_row.html.slim
  app/views/estimates/_outgoings_table.html.slim
  config/locales/en.yml
  spec/features/result_page_spec.rb
Labels: Approved, UAT

#363 EL-620 add new accordion section
  app/views/estimates/_limits_table.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
Labels: Approved

#362 EL-630: Hide empty calculation tables
  app/models/calculation_result.rb
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  spec/factories/api_results.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
Labels: Approved, UAT

#367 EL-627: Content cleanup
  config/locales/en.yml
Labels: Approved, UAT

#364 EL-616: Cookie config
  app/controllers/cookies_controller.rb
  config/environments/production.rb
Labels: Approved, UAT

#358 EL-618: Save as PDF
  .circleci/config.yml
  .gitignore
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/print.scss
  app/controllers/estimates_controller.rb
  app/views/estimates/show.html.slim
  app/views/layouts/print_application.html.slim
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  package.json
  puppeteer.config.cjs
  spec/features/result_page_spec.rb
  yarn.lock
Labels: Approved, UAT

#372 EL 636: Sentry fallback
  Gemfile
  Gemfile.lock
  app/lib/exception_notifier/templated_notifier.rb
  app/lib/feature_flags.rb
  app/mailers/exception_alert_mailer.rb
  config/environments/production.rb
  config/initializers/govuk_notify.rb
  config/initializers/sentry.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
  spec/spec_helper.rb
Labels: Approved, UAT

#376 EL-635 Error content and validation changes for partner flow
  app/forms/base_assets_form.rb
  app/forms/other_income_form.rb
  app/forms/outgoings_form.rb
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/partner_dependants_pages_spec.rb
  spec/features/partner_vehicle_pages_spec.rb
  spec/features/property_page_spec.rb
Labels: Approved, UAT

#370 EL-622 results page capital
  app/assets/stylesheets/results.scss
  app/helpers/results_helper.rb
  app/models/calculation_result.rb
  app/views/estimates/_capital_table.html.slim
  app/views/estimates/_disposable_capital_table.html.slim
  app/views/estimates/_income_row.html.slim
  app/views/estimates/_outgoings_row.html.slim
  app/views/estimates/_property_table.html.slim
  app/views/estimates/_vehicle_table.html.slim
  config/locales/en.yml
  spec/factories/api_results.rb
  spec/features/assets_page_spec.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Partner_with_passporting/CFE_submission/handles_can_submit_to_CFE.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/system/partner_passporting_spec.rb
Labels: Approved, UAT

#384 Enable partner on production
  helm_deploy/laa-estimate-eligibility/values-production.yaml
Labels: Approved

#385 EL-650: Create a feature flag for enabling controlled work
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#386 EL-654 Filter out all params from logs
  config/initializers/filter_parameter_logging.rb
Labels: Approved, UAT

#390 EL-659: Tell CFE about the level of help
  app/lib/cfe_connection.rb
  app/services/cfe_service.rb
  spec/features/level_of_help_page_spec.rb
  spec/support/navigation_helpers.rb
Labels: Approved, UAT
