Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-04, with the labels that each got.

#573 [EL-825] Update to CFE Civil staging
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved

#589 EL-834: Disable staging geckoboard
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
Labels: Approved

#585 EL-833: Check your answers matter type text
  app/lib/check_answers_fields.yml
  app/views/estimates/_check_answers_table.html.slim
  config/locales/en.yml
  spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
Labels: Approved, UAT

#587 EL-831: Show pensioner table if only partner has pensioner disregard applied
  app/models/calculation_result.rb
  spec/factories/api_results.rb
  spec/views/results_page/pensioner_content_spec.rb
Labels: Approved, UAT

#586 EL-832: Controlled work - Changes to content on 'Which type of matter is this?' screen
  README.md
  app/views/estimate_flow/matter_type.html.slim
  config/locales/en.yml
Labels: Approved

#576 EL-828: Use correct values for pensioner disregard table when there is a partner
  app/models/calculation_result.rb
  spec/views/results_page/pensioner_content_spec.rb
Labels: Approved, UAT

#588 EL-835: no-analytics mode
  app/controllers/application_controller.rb
  app/controllers/cookies_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/helpers/application_helper.rb
  app/services/analytics_service.rb
  app/services/choice_analytics_service.rb
  app/views/layouts/_analytics_body.html.slim
  app/views/layouts/_analytics_head.html.slim
  app/views/layouts/_footer.html.slim
  config/locales/en.layouts.yml
  config/routes.rb
  spec/features/no_analytics_mode_spec.rb
  spec/services/analytics_service_spec.rb
  spec/services/choice_analytics_service_spec.rb
Labels: Approved, UAT

#590 release asylum & immigration feature
  helm_deploy/laa-estimate-eligibility/values/production.yaml
Labels: Approved

#596 Ensure vehicle SMOD is never nil
  app/services/cfe_param_builders/vehicles.rb
Labels: bug, Approved

#592 EL-830: Copy update for student finance
  config/locales/en.yml
Labels: Approved, UAT

#583 EL-814: Making accessible PDFs from HTML layouts
  app/controllers/estimates_controller.rb
  app/views/estimates/_capital_table.html.slim
  app/views/estimates/_disposable_capital_table.html.slim
  app/views/estimates/_income_table.html.slim
  app/views/estimates/_outgoings_table.html.slim
  app/views/estimates/_property_table.html.slim
  app/views/estimates/_vehicle_table.html.slim
  app/views/estimates/print.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/print_application.html.slim
Labels: Approved, UAT

#571 EL-651: Pre-fill CW1
  .circleci/config.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/controlled_work_document_selections_controller.rb
  app/lib/controlled_work_mappings/cw1.yml
  app/models/controlled_work_document_content.rb
  app/services/controlled_work_document_population_service.rb
  app/services/controlled_work_document_value_mapping_service.rb
  lib/cw1-form.pdf
  spec/models/controlled_work_document_content_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved

#612 EL-842: Add SAG feature flag
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#611 EL-839: Remove A&I feature flag
  app/forms/applicant_form.rb
  app/helpers/applicant_helper.rb
  app/lib/case_details_section.rb
  app/lib/check_answers_fields.yml
  app/lib/feature_flags.rb
  app/models/check.rb
  app/services/cfe/submit_proceedings_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/level_of_help.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  spec/end_to_end/without_partner_spec.rb
  spec/factories/session.rb
  spec/features/number_fields_spec.rb
  spec/flows/asylum_and_immigration_flow_spec.rb
  spec/flows/certificated_non_passported_spec.rb
  spec/flows/certificated_passporting_spec.rb
  spec/flows/check_answers_flow_spec.rb
  spec/flows/controlled_work_spec.rb
  spec/forms/applicant_form_spec.rb
  spec/rails_helper.rb
  spec/services/cfe/submit_applicant_service_spec.rb
  spec/services/cfe/submit_proceedings_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
  spec/views/results_page/asylum_and_immigration_content_spec.rb
Labels: Approved, UAT

#613 EL-851: Blazer
  Gemfile
  Gemfile.lock
  README.md
  config/blazer.yml
  config/routes.rb
  db/migrate/20230426103352_install_blazer.rb
  db/migrate/20230426104843_add_blazer_permissions.rb
  db/schema.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
Labels: Approved, UAT

#615 EL-674 update the privacy policy and changelog
  app/views/change_logs/_banner.html.slim
  app/views/privacies/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#617 EL-820: Feature flags endpoint
  app/controllers/feature_flags_controller.rb
  app/lib/feature_flags.rb
  app/views/feature_flags/index.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/features/feature_flags_spec.rb
  spec/models/feature_flags_spec.rb
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#618 EL-857: Remove redundant link
  app/helpers/matter_type_helper.rb
  config/locales/en.yml
Labels: Approved, UAT

#623 EL-325: slack ci integration
  .circleci/config.yml
Labels: Approved

#597 [EL-798] Pre fill CW2 IMM form
  app/lib/controlled_work_mappings/cw1.yml
  app/lib/controlled_work_mappings/cw2.yml
  app/models/controlled_work_document_content.rb
  app/services/controlled_work_document_population_service.rb
  app/services/controlled_work_document_value_mapping_service.rb
  lib/cw2imm-form.pdf
  spec/models/controlled_work_document_content_spec.rb
  spec/services/controlled_work_document_value_mapping_service_spec.rb
Labels: Approved

#619 EL-727: Re-enable mod-sec with detection only
  helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved, UAT
