Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2023-02, with the labels that each got.

#392 EL-643: Controlled applicant pages
  app/forms/applicant_form.rb
  app/services/check_answers/applicant_section.rb
  app/services/submit_proceedings_service.rb
  app/views/estimate_flow/applicant.html.slim
  spec/support/navigation_helpers.rb
Labels: Approved, UAT

#388 Decision doesn't need to be defaulted
  app/models/calculation_result.rb
Labels: Approved

#391 EL-648 remove vehicle screens
  app/lib/capital_section.rb
  app/lib/partner_capital_section.rb
  app/models/calculation_result.rb
  app/models/estimate_model.rb
  app/services/cfe_service.rb
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimates/_capital_table.html.slim
  config/locales/en.yml
  spec/features/level_of_help_page_spec.rb
  spec/support/navigation_helpers.rb
Labels: Approved, UAT

#400 EL-647: Update outgoings page for controlled work
  app/forms/outgoings_form.rb
  app/forms/partner_outgoings_form.rb
  app/views/estimate_flow/outgoings.html.slim
  app/views/estimate_flow/partner_outgoings.html.slim
  config/locales/en.yml
  spec/features/level_of_help_page_spec.rb
Labels: Approved, UAT

#401 EL-646: Other income for controlled work
  app/forms/other_income_form.rb
  app/forms/partner_other_income_form.rb
  app/services/cfe_param_builders/irregular_income.rb
  app/views/estimate_flow/forms/_other_income.html.slim
  config/locales/en.yml
  spec/features/other_income_page_spec.rb
Labels: Approved, UAT

#394 EL-666: New start page for controlled work
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#403 EL-661: Change wording for level of help on check answers
  config/locales/en.yml
Labels: Approved, UAT

#387 EL-619: New confirmation panel on results page
  app/assets/stylesheets/results.scss
  app/models/calculation_result.rb
  app/views/estimates/_contribution_required.html.slim
  app/views/estimates/_eligible.html.slim
  app/views/estimates/_ineligible.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
  spec/features/assets_page_spec.rb
  spec/features/result_page_spec.rb
  spec/models/calculation_result_spec.rb
  spec/system/partner_passporting_spec.rb
  spec/system/vehicle_page_spec.rb
Labels: Approved, UAT

#402 EL-645 benefits guidance for controlled work
  app/controllers/benefits_controller.rb
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/partner_benefits/edit.html.slim
  app/views/partner_benefits/new.html.slim
  app/views/shared/_disregarded_benefits_sidebar.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#415 EL-679: Content cleanup
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/property_entry.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#398 EL 665 journey specific asset guidance
  app/views/estimate_flow/_certificated_property_sidebar.html.slim
  app/views/estimate_flow/_controlled_property_sidebar.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/partner_assets.html.slim
  app/views/estimate_flow/vehicle_details.html.slim
  config/locales/en.yml
  spec/features/property_page_spec.rb
Labels: Approved, UAT

#417 EL-699: New A&I feature flag
  .env.sample
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
Labels: Approved

#416 EL-649: Update results page for controlled work outcomes
  app/services/cfe_service.rb
  app/views/estimates/_certificated_contribution_required.html.slim
  app/views/estimates/_certificated_eligible.html.slim
  app/views/estimates/_certificated_ineligible.html.slim
  app/views/estimates/_controlled_eligible.html.slim
  app/views/estimates/_controlled_ineligible.html.slim
  app/views/estimates/_limits_table.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
  spec/features/result_page_spec.rb
  spec/system/accessibility_spec.rb
Labels: Approved, UAT

#413 EL-682: Add additional logging for analytics purposes
  app/controllers/accessibilities_controller.rb
  app/controllers/application_controller.rb
  app/controllers/benefits_controller.rb
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/controllers/cookies_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/privacies_controller.rb
  app/controllers/provider_users_controller.rb
  app/controllers/referrals_controller.rb
  app/controllers/start_controller.rb
  app/services/analytics_service.rb
  app/views/cookies/show.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/controllers/cookies_controller_spec.rb
Labels: Approved, UAT

#419 EL-678 remove cost of living feature flag
  app/lib/feature_flags.rb
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/forms/_assets.html.slim
  app/views/estimate_flow/forms/_other_income.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/shared/_cost_of_living.html.slim
  app/views/shared/_disregarded_benefits_details.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#405 EL-681 remove disregarded and passported benefits from suggestions
  app/lib/cfe_connection.rb
  app/models/benefit_model.rb
  spec/features/benefits_spec.rb
  spec/features/check_answers_page_spec.rb
  spec/features/partner_benefits_spec.rb
Labels: Approved, UAT

#421 EL-688 remove partner feature flag
  app/forms/applicant_form.rb
  app/lib/feature_flags.rb
  app/services/check_answers/applicant_section.rb
  app/services/submit_partner_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
  spec/features/applicant_page_spec.rb
  spec/features/employment_page_spec.rb
  spec/features/property_page_spec.rb
  spec/features/result_page_spec.rb
  spec/rails_helper.rb
  spec/support/navigation_helpers.rb
Labels: Approved, UAT

#420 EL-680: Show check answers but not limits on print screen
  app/controllers/estimates_controller.rb
  app/views/estimates/_check_answers_table.html.slim
  app/views/estimates/check_answers.html.slim
  app/views/estimates/print.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#423 EL-652: Stop using git-crypt
  .circleci/config.yml
  .gitattributes
  README.md
  bin/uat_deployment
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/deployment.yaml
  helm_deploy/laa-estimate-eligibility/templates/secret.yaml
  helm_deploy/laa-estimate-eligibility/values-production.yaml
  helm_deploy/laa-estimate-eligibility/values-staging.yaml
  helm_deploy/laa-estimate-eligibility/values-uat.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#418 EL-686 Replace date with level of work in sidebar
  app/helpers/applicant_helper.rb
  app/helpers/assets_helper.rb
  app/helpers/dependants_helper.rb
  app/helpers/outgoings_helper.rb
  app/helpers/property_helper.rb
  app/presenters/check_answers_presenter.rb
  app/views/benefits/edit.html.slim
  app/views/benefits/new.html.slim
  app/views/estimate_flow/_certificated_partner_property_sidebar.html.slim
  app/views/estimate_flow/_certificated_property_sidebar.html.slim
  app/views/estimate_flow/_controlled_partner_property_sidebar.html.slim
  app/views/estimate_flow/_controlled_property_sidebar.html.slim
  app/views/estimate_flow/_partner_property_sidebar.html.slim
  app/views/estimate_flow/_property_sidebar.html.slim
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/assets.html.slim
  app/views/estimate_flow/benefits.html.slim
  app/views/estimate_flow/dependant_details.html.slim
  app/views/estimate_flow/employment.html.slim
  app/views/estimate_flow/housing_benefit.html.slim
  app/views/estimate_flow/housing_benefit_details.html.slim
  app/views/estimate_flow/level_of_help.html.slim
  app/views/estimate_flow/matter_type.html.slim
  app/views/estimate_flow/other_income.html.slim
  app/views/estimate_flow/outgoings.html.slim
  app/views/estimate_flow/partner_assets.html.slim
  app/views/estimate_flow/partner_benefits.html.slim
  app/views/estimate_flow/partner_dependant_details.html.slim
  app/views/estimate_flow/partner_details.html.slim
  app/views/estimate_flow/partner_employment.html.slim
  app/views/estimate_flow/partner_housing_benefit.html.slim
  app/views/estimate_flow/partner_housing_benefit_details.html.slim
  app/views/estimate_flow/partner_other_income.html.slim
  app/views/estimate_flow/partner_outgoings.html.slim
  app/views/estimate_flow/partner_property.html.slim
  app/views/estimate_flow/partner_property_entry.html.slim
  app/views/estimate_flow/partner_vehicle.html.slim
  app/views/estimate_flow/partner_vehicle_details.html.slim
  app/views/estimate_flow/property.html.slim
  app/views/estimate_flow/property_entry.html.slim
  app/views/estimate_flow/tribunal.html.slim
  app/views/estimate_flow/vehicle.html.slim
  app/views/estimate_flow/vehicle_details.html.slim
  app/views/estimates/check_answers.html.slim
  app/views/partner_benefits/edit.html.slim
  app/views/partner_benefits/new.html.slim
  app/views/provider_users/show.html.slim
  app/views/shared/_disregarded_benefits_sidebar.html.slim
  app/views/shared/_question_sidebar.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  spec/features/property_page_spec.rb
Labels: Approved, UAT

#433 EL-703: Upper tribunal start page
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#431 EL-561: Content on referral page
  app/views/referrals/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#430 EL-709: De-identify user in logs
  app/controllers/application_controller.rb
  app/controllers/benefits_controller.rb
  app/controllers/build_estimates_controller.rb
  app/controllers/check_answers_controller.rb
  app/controllers/check_benefits_answers_controller.rb
  app/controllers/check_partner_benefits_answers_controller.rb
  app/controllers/estimate_flow_controller.rb
  app/controllers/estimates_controller.rb
  app/controllers/partner_benefits_controller.rb
  app/helpers/application_helper.rb
  app/services/analytics_service.rb
  app/services/base_cfe_service.rb
  app/services/cfe_service.rb
  app/services/submit_applicant_service.rb
  app/services/submit_assets_service.rb
  app/services/submit_benefits_service.rb
  app/services/submit_dependants_service.rb
  app/services/submit_employment_income_service.rb
  app/services/submit_irregular_income_service.rb
  app/services/submit_partner_service.rb
  app/services/submit_proceedings_service.rb
  app/services/submit_regular_transactions_service.rb
  app/services/submit_vehicle_service.rb
  app/views/estimates/_check_answer.html.slim
  app/views/estimates/_check_answers_table.html.slim
  app/views/estimates/_money_and_frequency_check_answer.slim
  app/views/estimates/check_answers.html.slim
  app/views/estimates/show.html.slim
Labels: Approved, UAT

#432 EL-708: New level of help content
  app/views/estimate_flow/level_of_help.html.slim
  app/views/shared/_question_sidebar.html.slim
  app/views/shared/_related_content.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#442 EL-714: Update controlled evidence wording
  config/locales/en.yml
Labels: Approved, UAT

#447 EL-721: Enable Sentry
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#448 EL-716: Add postgres to UAT environment
  .circleci/config.yml
  Dockerfile
  helm_deploy/laa-estimate-eligibility/Chart.lock
  helm_deploy/laa-estimate-eligibility/Chart.yaml
  helm_deploy/laa-estimate-eligibility/charts/postgresql-11.9.13.tgz
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Approved

#440 EL-712: Main home equity disregard always displays as £100k.
  app/models/calculation_result.rb
  spec/factories/api_results.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/models/calculation_result_spec.rb
Labels: Approved, UAT

#452 El 640: wording updates
  app/views/estimate_flow/forms/_dependant_details.html.slim
  app/views/estimate_flow/forms/_outgoings.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#446 EL-711: Cost of sale bug
  app/models/calculation_result.rb
  config/locales/en.yml
  spec/factories/api_results.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/models/calculation_result_spec.rb
Labels: Approved, UAT

#449 EL-713: Start using postgres to record analytics
  .circleci/config.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/lib/exception_notifier/templated_notifier.rb
  app/models/analytics_event.rb
  app/models/application_record.rb
  app/services/analytics_service.rb
  app/services/error_service.rb
  config/application.rb
  config/database.yml
  db/migrate/20230221125618_create_analytics_events.rb
  db/schema.rb
  spec/features/result_page_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/records_every_step_of_the_journey_in_analytics_events.yml
  spec/services/analytics_service_spec.rb
  spec/services/error_service_spec.rb
Labels: Approved, UAT

#424 EL-696 passporting asylum support applications
  app/controllers/flow/handler.rb
  app/forms/applicant_form.rb
  app/forms/asylum_support_form.rb
  app/lib/applicant_details_section.rb
  app/lib/capital_section.rb
  app/lib/case_details_section.rb
  app/lib/check_answers_fields.yml
  app/lib/income_section.rb
  app/lib/partner_capital_section.rb
  app/lib/partner_income_section.rb
  app/lib/partner_section.rb
  app/lib/steps_helper.rb
  app/models/estimate_model.rb
  app/services/check_answers/section_id_finder.rb
  app/services/submit_applicant_service.rb
  app/services/submit_assets_service.rb
  app/views/estimate_flow/asylum_support.html.slim
  config/locales/en.yml
  spec/features/asylum_and_immigration_spec.rb
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
  spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
  spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
  spec/services/submit_applicant_service_spec.rb
Labels: Approved, UAT

#451 EL 638 matter type page certificated
  app/forms/applicant_form.rb
  app/forms/matter_type_form.rb
  app/helpers/applicant_helper.rb
  app/helpers/matter_type_helper.rb
  app/lib/applicant_details_section.rb
  app/lib/capital_section.rb
  app/lib/case_details_section.rb
  app/lib/check_answers_fields.yml
  app/lib/income_section.rb
  app/lib/partner_capital_section.rb
  app/lib/partner_income_section.rb
  app/lib/partner_section.rb
  app/models/estimate_model.rb
  app/services/submit_assets_service.rb
  app/services/submit_proceedings_service.rb
  app/views/estimate_flow/applicant.html.slim
  app/views/estimate_flow/matter_type.html.slim
  config/locales/en.yml
  spec/features/applicant_page_spec.rb
  spec/features/asylum_and_immigration_spec.rb
  spec/features/result_page_spec.rb
  spec/services/submit_proceedings_service_spec.rb
  spec/support/navigation_helpers.rb
Labels: Approved, UAT

#454 EL-705 add certificated asylum support question
  app/helpers/asylum_support_helper.rb
  app/lib/case_details_section.rb
  app/views/estimate_flow/asylum_support.html.slim
  config/locales/en.yml
  spec/features/asylum_and_immigration_spec.rb
Labels: Approved

#453 EL-715: push to geckoboard
  Gemfile
  Gemfile.lock
  README.md
  app/services/metrics_service.rb
  config/initializers/geckoboard.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/cronjob-generate-metrics.yaml
  helm_deploy/laa-estimate-eligibility/values/production.yaml
  helm_deploy/laa-estimate-eligibility/values/staging.yaml
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
  lib/tasks/jobs/metrics.rake
  spec/factories/analytics_event.rb
  spec/services/metrics_service_spec.rb
Labels: Approved, UAT

#457 EL-698 & 706 results screens
  app/controllers/estimates_controller.rb
  app/views/estimates/_asylum_support_certificated_eligible.html.slim
  app/views/estimates/_asylum_support_controlled_eligible.html.slim
  app/views/estimates/_evidence.html.slim
  app/views/estimates/_limits_table.html.slim
  app/views/estimates/_result_panel_content.html.slim
  app/views/estimates/print.html.slim
  app/views/estimates/show.html.slim
  config/locales/en.yml
  spec/features/asylum_and_immigration_spec.rb
  spec/views/estimates/show.html.slim_spec.rb
Labels: Approved, UAT

#463 Fix forgotten UAT switch
  helm_deploy/laa-estimate-eligibility/values/uat.yaml
Labels: Ready For Review
