Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-07, with the labels that each got.

#1433 update puppeteer
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1440 Add note about warnings when updating chromedriver
  README.md
Labels: Approved

#1441 EL-1427 New content on start page
  app/services/external_link_service.rb
  app/views/shared/_related_without_new_tab.html.slim
  app/views/start/index.html.slim
  config/locales/en.yml
  spec/features/basic_auth_spec.rb
  spec/features/maintenance_mode_spec.rb
Labels: Approved, UAT

#1446 EL-1484: CCQ Accessibility Statement
  config/locales/en.yml
Labels: Approved, UAT

#1439 EL-1587 update level of help content
  app/views/question_flow/level_of_help.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1438 EL-1606 Logout page and signed in banner for LAA portal integration
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/admins/sessions_controller.rb
  app/controllers/application_controller.rb
  app/controllers/providers/omniauth_callbacks_controller.rb
  app/controllers/providers/sessions_controller.rb
  app/controllers/start_controller.rb
  app/helpers/application_helper.rb
  app/lib/laa_portal/saml_setup.rb
  app/lib/laa_portal/saml_strategy.rb
  app/models/admin.rb
  app/models/provider.rb
  app/views/admins/sessions/new.html.slim
  app/views/layouts/application.html.slim
  app/views/providers/sessions/new.html.slim
  app/views/start/index.html.slim
  app/views/start/portal_signed_out.html.slim
  config/initializers/devise.rb
  config/initializers/omniauth.rb
  config/locales/en.yml
  config/routes.rb
  config/saml/certificates/cert-production.pem
  config/saml/certificates/cert-staging.pem
  config/saml/certificates/cert-uat.pem
  config/saml/metadata/dev.xml
  config/saml/metadata/portal-idp-dev.xml
  config/saml/metadata/portal-idp-prod.xml
  config/saml/metadata/portal-idp-stg.xml
  config/saml/metadata/portal-idp-uat.xml
  config/saml/metadata/stg.xml
  config/saml/metadata/uat.xml
  db/migrate/20240615073559_create_providers.rb
  db/schema.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/controllers/oauth_redirects_controller_spec.rb
  spec/factories/mock_saml_auth.rb
  spec/factories/providers.rb
  spec/features/provider_authentication_spec.rb
  spec/features/provider_login_spec.rb
  spec/rails_helper.rb
Labels: Approved, UAT

#1457 fix the GA delete action
  .github/actions/delete-uat-release/action.yml
Labels: Approved

#1458 Revert "fix the GA delete action"
  .github/actions/delete-uat-release/action.yml
Labels: Approved

#1436 EL-1596: content changes for partner outgoings, assets, property
  app/views/question_flow/forms/_other_income.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1451 EL-1625 portal privacy text
  app/views/privacies/show.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1450 EL-1614: Portal Metrics
  README.md
  app/controllers/providers/omniauth_callbacks_controller.rb
  app/controllers/results_controller.rb
  app/models/completed_user_journey.rb
  app/models/provider.rb
  app/services/journey_logger_service.rb
  config/saml/metadata/uat.xml
  db/migrate/20240715104344_add_office_code_to_provider.rb
  db/schema.rb
  spec/features/provider_authentication_spec.rb
  spec/features/provider_login_spec.rb
  spec/services/journey_logger_service_spec.rb
Labels: Approved, UAT

#1456 EL-1606 Add production metadata
  config/saml/metadata/prod.xml
Labels: Approved

#1463 Portal metadata change
  config/saml/metadata/portal-idp-prd.xml
  config/saml/metadata/portal-idp-prod.xml
  config/saml/metadata/prod.xml
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
Labels: Approved

#1464 [Snyk] Security upgrade sentry-rails from 5.18.1 to 5.18.2
  Gemfile
  Gemfile.lock
Labels: Approved

#1466 Update pipeline
  .circleci/config.yml
Labels: Ready For Review

#1468 update puppeteer: part deux
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1470 BUG: Patch rails admin data types to fix admin panel
  lib/rails_admin/config/fields/types/all.rb
  lib/rails_admin/config/fields/types/timestamptz.rb
Labels: Approved

#1461 EL-1632 delete portal users after 1 week
  app/services/old_data_removal_service.rb
  spec/factories/providers.rb
  spec/services/old_data_removal_service_spec.rb
Labels: Approved, UAT

#1472 EL-1583: Shared Ownership feature flag
  app/lib/feature_flags.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/rails_helper.rb
Labels: Approved, UAT

#1474 EL-1659: Add rails admin type override
  app/overrides/rails_admin/type_override.rb
  config/application.rb
  lib/rails_admin/config/fields/types/all.rb
  lib/rails_admin/config/fields/types/timestamptz.rb
Labels: Approved

#1476 EL-1660 Add error logging for SAML Logout request error
  app/lib/laa_portal/saml_strategy.rb
Labels: Approved
