Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-12, with the labels that each got.

#1632 EL-1833 (part 2) add data_migration
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  README.md
  db/data/20241101122511_populate_early_eligibility_result_in_completed_user_journeys.rb
  db/data_schema.rb
  db/schema.rb
  lib/tasks/jobs/migrations.rake
Labels: Approved

#1689 EL-1833: Turn off maintenance mode
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
Labels: Ready For Review

#1691 Remove prod and staging approval steps
  .circleci/config.yml
Labels: Ready For Review

#1684 EL-1810: Track when results are saved as PDF
  app/views/results/show.html.slim
Labels: Ready For Review

#1678 EL-1793: Remove redundant geckoboard code
  Gemfile
  Gemfile.lock
  README.md
  app/services/metrics/for_key_metric_dashboard_service.rb
  app/services/metrics/for_user_journey_dashboard_service.rb
  app/services/metrics_service.rb
  config/initializers/geckoboard.rb
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/templates/cronjob-generate-metrics.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  lib/tasks/jobs/metrics.rake
  spec/services/metrics/for_key_metric_dashboard_service_spec.rb
  spec/services/metrics/for_user_journey_dashboard_service_spec.rb
  spec/services/metrics_service_spec.rb
Labels: Approved

#1680 EL-1911: Add meta-description
  app/views/layouts/shared/_header.html.slim
Labels: Approved, UAT

#1693 EL-1810: CCQ: Track when results are saved as PDF, Part 2
  app/views/results/_under_eighteen_next_steps.html.slim
Labels: Approved

#1698 EL-1801: Investigate why specific fields shown as 0 when below £1.00
  app/services/cfe_param_builders/capitals.rb
  app/services/cfe_param_builders/regular_transactions.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
Labels: Approved, UAT

#1708 Add a production hold to deployments
  .circleci/config.yml
Labels: Approved
