Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-08, with the labels that each got.

#1482 Puppeteer 22.15 upgrade to Chrome 127
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1473 EL-1629: Remove `legacy_assets_no_reveal` & `legacy_housing_benefit_without_reveals` feature flag
  app/controllers/instant_sessions_controller.rb
  app/forms/assets_form.rb
  app/forms/housing_costs_form.rb
  app/lib/check_answers_fields_legacy.yml
  app/lib/feature_flags.rb
  app/models/check.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/check_answers/section_lister_service.rb
  app/views/question_flow/forms/_assets.html.slim
  app/views/question_flow/housing_costs.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/end_to_end/result_page_variations_spec.rb
  spec/features/instant_sessions_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/housing_costs_form_spec.rb
  spec/forms/partner_assets_form_spec.rb
  spec/models/client_assets_form_spec.rb
  spec/models/housing_costs_form_spec.rb
  spec/models/partner_assets_form_spec.rb
  spec/rails_helper.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/views/check_answers_page/client_content/assets_spec.rb
  spec/views/check_answers_page/client_content/housing_benefit_spec.rb
  spec/views/check_answers_page/partner_content/assets_spec.rb
Labels: Approved, UAT

#1484 Use AlphaNumeric.alpha rather than String.random
  spec/features/provider_authentication_spec.rb
Labels: Ready For Review

#1485 EL-1645 improve check answers coverage
  spec/flows/certificated_passporting_spec.rb
  spec/flows/controlled_work_spec.rb
  spec/flows/under_eighteen_flow_spec.rb
  spec/forms/benefit_details_form_spec.rb
  spec/forms/controlled_legal_representation_form_spec.rb
  spec/forms/employment_status_form_spec.rb
  spec/forms/other_income_form_spec.rb
Labels: Approved

#1487 El 1630 model annotation gem
  Gemfile
  Gemfile.lock
  app/models/admin.rb
  app/models/analytics_event.rb
  app/models/banner.rb
  app/models/change_log.rb
  app/models/completed_user_journey.rb
  app/models/feature_flag_override.rb
  app/models/freetext_feedback.rb
  app/models/issue.rb
  app/models/issue_update.rb
  app/models/provider.rb
  app/models/satisfaction_feedback.rb
Labels: Approved, UAT

#1488 EL-1668 Refactor change answers controller
  app/controllers/change_answers_controller.rb
  app/controllers/question_flow_controller.rb
  app/lib/steps/helper.rb
  app/lib/steps/logic.rb
  app/lib/steps/non_financial_section.rb
  app/models/cfe_result.rb
  app/models/check.rb
  spec/flows/early_result_change_answers_flow_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved

#1505 EL-1691 add gemfile rexml constraint to prevent accidental downgrade
  Gemfile
  Gemfile.lock
Labels: Approved

#1504 EL-1693 exclude Rails and puppeteer from combined dependency lists
  .github/dependabot.yml
Labels: Approved

#1486 EL-1660 Add reset_session to login callback
  app/controllers/providers/omniauth_callbacks_controller.rb
  config/saml/metadata/uat.xml
Labels: Approved

#1515 EL-1640 Removing delete pvc command. Not required
  .github/actions/delete-uat-release/action.yml
Labels: Approved, UAT

#1517 EL-1633: Remove text from Partner Other property details page
  app/views/question_flow/_additional_property_section.html.slim
  config/locales/en.yml
Labels: Approved, UAT
