Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-05, with the labels that each got.

#1354 EL-1491 remove feature flags
  app/controllers/instant_sessions_controller.rb
  app/forms/other_income_form.rb
  app/forms/outgoings_form.rb
  app/lib/check_answers_fields.yml
  app/lib/feature_flags.rb
  app/models/check.rb
  app/models/dependant_income_model.rb
  app/services/cfe_param_builders/irregular_income.rb
  app/services/cfe_param_builders/regular_transactions.rb
  app/services/check_answers/section_lister_service.rb
  app/views/question_flow/forms/_other_income.html.slim
  app/views/question_flow/forms/_outgoings.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  spec/end_to_end/other_income_spec.rb
  spec/end_to_end/result_page_variations_spec.rb
  spec/end_to_end/with_partner_spec.rb
  spec/end_to_end/without_partner_spec.rb
  spec/factories/session.rb
  spec/features/instant_sessions_spec.rb
  spec/features/number_fields_spec.rb
  spec/fixtures/vcr_cassettes/Change_answers_after_early_result/when_starting_as_ineligible_on_gross_income/with_a_full-stack_VCR_environment/with_a_partner/can_change_to_below_threshold_with_partner_above_and_submit_correctly.yml
  spec/fixtures/vcr_cassettes/Ineligible_result_on_result_screen/displays_3_ineligible_summary_boxes.yml
  spec/flows/certificated_non_passported_spec.rb
  spec/flows/early_result_spec.rb
  spec/flows/summary_box_classes_spec.rb
  spec/forms/dependant_details_form_spec.rb
  spec/forms/dependant_income_details_form_spec.rb
  spec/forms/other_income_form_spec.rb
  spec/forms/outgoings_form_spec.rb
  spec/forms/partner_other_income_form_spec.rb
  spec/forms/partner_outgoings_form_spec.rb
  spec/models/dependant_income_model_spec.rb
  spec/rails_helper.rb
  spec/services/cfe/irregular_income_payload_service_spec.rb
  spec/services/cfe/partner_payload_service_spec.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
  spec/support/flow_helpers.rb
  spec/views/check_answers_page/client_content/other_income_spec.rb
  spec/views/check_answers_page/client_content/outgoings_spec.rb
  spec/views/check_answers_page/partner_content/other_income_spec.rb
  spec/views/check_answers_page/partner_content/outgoings_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
Labels: Approved, UAT

#1349 EL-1417: Use new typography scale from design system
  app/assets/stylesheets/application.sass.scss
Labels: Approved, UAT

#1363 EL-1511 put validation back in, removed in error
  app/forms/other_income_form.rb
  app/forms/outgoings_form.rb
Labels: Approved

#1367 Add default values to feature flags
  app/lib/feature_flags.rb
Labels: Approved

#1374 Puppeteer 22.8.0
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1377 Puppeteer 2282
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1373 EL-1460 add MTR accelerated feature flag
  app/lib/feature_flags.rb
Labels: Approved

#1375 EL-1495 Ruby 3.3.1 upgrade
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  .github/workflows/rubocop.yml
  .ruby-version
  Dockerfile
  Dockerfile_browser_tools.dockerfile
  Gemfile
  Gemfile.lock
  spec/system/feedback_spec.rb
Labels: Approved, UAT

#1381 Sentry Browser JS v8 fixes
  app/javascript/application.js
  package.json
  yarn.lock
Labels: javascript, Ready For Review

#1387 Puppeteer 22.9.0
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1390 [Snyk] Security upgrade propshaft from 0.8.0 to 0.9.0
  Gemfile
  Gemfile.lock
Labels: Approved

#1396 EL-1522: Client and Partner Other Income pages content update
  app/views/question_flow/forms/_other_income.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1401 update puppeteer to 22.10
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1391 El 1518 mortgage or loan
  app/helpers/checks_helper.rb
  app/helpers/property_helper.rb
  app/views/checks/_check_answers_table.html.slim
  app/views/question_flow/mortgage_or_loan_payment.html.slim
  config/locales/en.yml
  spec/forms/mortgage_or_loan_payment_form_spec.rb
Labels: Approved, UAT

#1389 El 1517 accel mtr property entry
  app/helpers/checks_helper.rb
  app/helpers/property_helper.rb
  app/views/checks/_check_answers_table.html.slim
  app/views/question_flow/property_entry.html.slim
  config/locales/en.yml
  spec/end_to_end/without_partner_spec.rb
  spec/forms/property_entry_form_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
  spec/views/results_page/partially_owned_property_content_spec.rb
Labels: Approved, UAT

#1393 EL-1520: Update the view on the 'Add benefit details' page
  app/views/question_flow/forms/_benefit_details.html.slim
  config/locales/en.yml
Labels: Approved, UAT
