Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-10, with the labels that each got.

#1558 EL-1752 update passporting hint content
  app/views/question_flow/applicant.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1560 EL-1726: Implement Gajira in Github Workflow
  .github/workflows/gajira.yml
Labels: Approved

#1567 EL-1726 Bugfix Gajira GH action
  .github/workflows/gajira.yml
Labels: Approved

#1573 EL-1726: Gajira part 3
  .github/workflows/gajira.yml
Labels: Approved

#1570 El 1706 remove session reset
  app/controllers/providers/omniauth_callbacks_controller.rb
Labels: Approved

#1571 EL-1773 remove old content from results page
  app/views/results/_limits_table.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1576 EL-1726: Gajira part 4
  .github/workflows/gajira.yml
Labels: Approved

#1580 EL-1726: Gajira part 5
  .github/workflows/gajira.yml
Labels: Approved

#1582 EL-1726: Gajira part 6
  .github/workflows/gajira.yml
Labels: Approved

#1584 EL-1726: Gajira part 7
  .github/workflows/gajira.yml
Labels: Approved

#1586 EL-1726: Gajira part 8
  .github/workflows/gajira.yml
Labels: Ready For Review

#1565 EL-1770 remove hexapdf
  Gemfile
  Gemfile.lock
  app/services/pdf_service.rb
Labels: Approved, UAT

#1592 EL-1756: Add `early_result_type` to CompletedUserJourney
  app/models/completed_user_journey.rb
  db/migrate/20241010143225_add_early_result_type_to_completed_user_journeys.rb
  db/schema.rb
Labels: Approved, UAT

#1590 EL-1758: Remove Portal user emails from CCQ Admin
  config/initializers/rails_admin.rb
Labels: Approved, UAT

#1550 EL-1745 Check Answers display
  app/models/check.rb
  app/services/check_answers/section_lister_service.rb
  spec/flows/early_result_spec.rb
  spec/flows/under_eighteen_flow_spec.rb
Labels: Approved, UAT

#1599 BUGFIX: CivMeans7 Welsh (Rent)
  app/lib/controlled_work_mappings/civ_means_7_welsh_new.yml
Labels: Approved, UAT

#1604 EL-1781 Rails update to 7.2.1
  Gemfile
  Gemfile.lock
  app/forms/additional_property_details_form.rb
  app/forms/benefit_details_form.rb
  app/forms/client_assets_form.rb
  app/forms/dependant_income_details_form.rb
  app/forms/income_form.rb
  app/forms/partner_assets_form.rb
  app/forms/vehicles_details_form.rb
  spec/rails_helper.rb
Labels: Approved, UAT

#1600 EL-1787 update puppetteer to 23.5.3
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1615 release new cw forms
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Ready For Review

#1614 EL-1814: Manual upgrade of puppeteer to 23.6.0
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1594 EL-1725 EE back button
  app/views/results/show.html.slim
  spec/flows/early_result_spec.rb
Labels: Approved, UAT
