Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2024-03, with the labels that each got.

#1251 EL-1347: Improve PDF link names
  app/helpers/applicant_helper.rb
  app/helpers/assets_helper.rb
  app/helpers/asylum_support_helper.rb
  app/helpers/dependants_helper.rb
  app/helpers/employment_helper.rb
  app/helpers/property_helper.rb
  app/helpers/vehicle_helper.rb
  app/views/question_flow/vehicle.html.slim
  app/views/shared/_disregarded_benefits_sidebar.html.slim
  app/views/shared/_related_content.html.slim
  config/locales/en.yml
  spec/forms/applicant_form_spec.rb
  spec/forms/assets_form_spec.rb
  spec/forms/asylum_support_form_spec.rb
  spec/forms/outgoings_form_spec.rb
  spec/forms/partner_assets_form_spec.rb
  spec/forms/partner_outgoings_form_spec.rb
  spec/forms/vehicles_details_form_spec.rb
Labels: Approved, UAT

#1261 EL-1377 dont try to send income or outgoings forms if they are invalid
  app/services/cfe/regular_transactions_payload_service.rb
  app/services/cfe_param_builders/regular_transactions.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
Labels: Approved, UAT

#1284 EL-1342 tidy up content on applicant page
  app/views/question_flow/applicant.html.slim
  config/locales/en.yml
Labels: Approved

#1288 EL-1396 CFE DB Upgrade: Enable maintenance mode in Production
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  public/maintenance.html
Labels: Approved, UAT

#1291 El1403 disable error catch for tests
  spec/features/invalid_session_spec.rb
  spec/rails_helper.rb
  spec/services/analytics_service_spec.rb
  spec/services/choice_analytics_service_spec.rb
  spec/services/error_service_spec.rb
  spec/services/journey_log_update_service_spec.rb
  spec/services/journey_logger_service_spec.rb
Labels: Approved

#1292 El 1353 tag docker images with branch
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
Labels: Approved

#1295 use main branch image for running circle tests
  .circleci/config.yml
Labels: question, Approved

#1263 EL-1308 - merge case and applicant sections into non finance section
  app/controllers/change_answers_controller.rb
  app/lib/steps/applicant_details_section.rb
  app/lib/steps/helper.rb
  app/lib/steps/non_financial_section.rb
Labels: Approved, UAT

#1287 EL-1385 EE results page
  app/assets/stylesheets/results.scss
  app/controllers/results_controller.rb
  app/models/calculation_result.rb
  app/views/results/_capital_table.html.slim
  app/views/results/_outgoings_table.html.slim
  app/views/results/_summary.html.slim
  config/locales/en.yml
  spec/end_to_end/result_page_variations_spec.rb
Labels: Approved, UAT

#1285 El-1352 Debian based image with puppeteer
  .circleci/config.yml
  .dockerignore
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile
  Dockerfile_browser_tools.dockerfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: Approved, UAT

#1299 EL-1352 follow-up - remove left-over testing artifacts
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
Labels: Approved

#1308 Puppeteer 2250
  .circleci/config.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1304 EL-1408: Add aria labels to 'See Calculation' links
  app/views/results/_summary.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1286 EL-1365: Switch on client/partner other income and outgoings conditional reveals
  app/controllers/instant_sessions_controller.rb
  app/forms/other_income_form.rb
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/factories/session.rb
  spec/features/instant_sessions_spec.rb
  spec/forms/other_income_form_spec.rb
  spec/forms/partner_other_income_form_spec.rb
  spec/forms/partner_outgoings_form_spec.rb
Labels: Approved, UAT

#1300 EL-1407 change answers links with aria-label
  app/views/checks/_check_answer.html.slim
  app/views/checks/_check_answers_table.html.slim
  config/locales/en.yml
Labels: Approved

#1301 EL-1344: Feedback, screen reader notification
  app/javascript/feedback.js
  app/views/layouts/_feedback.html.slim
  config/locales/en.yml
  spec/system/feedback_spec.rb
Labels: Approved, UAT

#1314 EL-1428: Show capital eligible when gross ineligible
  spec/fixtures/vcr_cassettes/Change_answers_after_early_result/can_handle_a_switch_from_passporting_to_not.yml
  spec/fixtures/vcr_cassettes/Change_answers_after_early_result/when_starting_as_ineligible_on_gross_income/with_a_full-stack_VCR_environment/changes_client_age_to_under_18_with_income.yml
  spec/fixtures/vcr_cassettes/Change_answers_after_early_result/when_starting_as_ineligible_on_gross_income/with_a_full-stack_VCR_environment/when_the_user_clicks_on_back_links/correctly_works_out_relevant_information.yml
  spec/fixtures/vcr_cassettes/Change_answers_after_early_result/when_starting_as_ineligible_on_gross_income/with_a_full-stack_VCR_environment/with_a_partner/can_change_to_below_threshold_with_partner_above_and_submit_correctly.yml
  spec/fixtures/vcr_cassettes/Ineligible_result_on_result_screen/displays_3_ineligible_summary_boxes.yml
  spec/flows/summary_box_classes_spec.rb
Labels: Approved

#1312 EL-1345: Ensure details components work with screenreaders
  app/views/question_flow/applicant.html.slim
  app/views/question_flow/dependant_details.html.slim
Labels: Approved, UAT

#1315 EL-1409: Assign correct attributes to 'frequency' legend
  app/views/question_flow/forms/_other_income.html.slim
  app/views/question_flow/forms/_outgoings.html.slim
Labels: Approved, UAT

#1320 Upgrade puppeteer to 22.6.0
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1305 EL-1379: 'check answers' screen, updated heading structure and layout
  app/lib/check_answers_fields.yml
  app/lib/check_answers_fields_old_flow.yml
  app/services/check_answers/section_lister_service.rb
  app/views/checks/_check_answers_table.html.slim
  app/views/checks/check_answers.html.slim
  config/locales/en.yml
  spec/views/check_answers_page/client_content/special_client_types/passported_client_spec.rb
  spec/views/check_answers_page/client_content/special_client_types/under_eighteen_client_spec.rb
Labels: Approved, UAT

#1278 El 1339 parallel specs
  .circleci/config.yml
  .rspec_parallel
  Gemfile
  Gemfile.lock
  config/database.yml
  lib/tasks/jobs/simplecov_coverage.rake
  spec/spec_helper.rb
  spec/system/feedback_spec.rb
Labels: Approved
