Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2025-06, with the labels that each got.

#1890 el-2368: Use eager loading for issue updates
  app/models/issue.rb
  app/views/updates/index.html.slim
Labels: Approved, discussion

#1898 el-2409-part-1: update psql-client
  Dockerfile
Labels: Approved

#1886 EL-2341: Update CCQ with new `govuk-frontend` rebrand
  Gemfile.lock
  app/helpers/application_helper.rb
  app/views/layouts/_footer.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/devise.html.slim
  app/views/layouts/download_application.html.slim
  app/views/layouts/shared/_header.html.slim
  config/locales/en.yml
  public/404.html
  public/422.html
  public/500.html
  public/apple-touch-icon-precomposed.png
  public/apple-touch-icon.png
  public/crest.svg
  public/favicon.ico
  public/favicon.svg
  public/govuk-icon-180.png
  public/govuk-icon-mask.svg
  public/govuk-opengraph-image.png
  public/maintenance.html
  public/manifest.json
Labels: Approved, UAT

#1904 EL-2446: bump puppeteer from 24.10.1 to 24.10.2
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT
