Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2025-05, with the labels that each got.

#1858 el-2803: enable shared ownership in production
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
Labels: Approved

#1849 el-2213: add rake task to delete feedbacks
  lib/tasks/delete_feedback.rake
  spec/lib/tasks/delete_feedback_spec.rb
Labels: Approved

#1862 Puppeteer 2480
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1868 el-2305: prevent ee banner being displayed for passported checks
  app/models/check.rb
  app/views/question_flow/_early_result_banner.html.slim
  spec/flows/early_result_spec.rb
Labels: Ready For Review

#1872 EL-2332: Update puppeteer to 24.8.2
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1873 el-2308: remove shared ownership flag
  app/helpers/forms_helper.rb
  app/lib/feature_flags.rb
  app/views/start/index.html.slim
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/flows/cannot_use_service_flow_spec.rb
  spec/flows/change_answers_flow_spec.rb
  spec/flows/shared_ownership_flow_spec.rb
  spec/forms/additional_property_form_spec.rb
  spec/forms/property_form_spec.rb
  spec/forms/property_landlord_form_spec.rb
  spec/forms/shared_ownership_housing_costs_form_spec.rb
  spec/rails_helper.rb
  spec/services/cfe/assets_payload_service_spec.rb
  spec/views/results_page/housing_outgoings_content_spec.rb
Labels: Approved, UAT
