Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2025-03, with the labels that each got.

#1766 EL-2108 delete pvc command to github action
  .github/actions/delete-uat-release/action.yml
Labels: Ready For Review

#1772 EL-1577 shared ownership property change
  app/forms/property_entry_form.rb
  app/forms/property_form.rb
  app/helpers/forms_helper.rb
  app/services/cfe/assets_payload_service.rb
  config/locales/en.yml
  spec/factories/session.rb
  spec/forms/additional_property_form_spec.rb
  spec/forms/property_form_spec.rb
  spec/rails_helper.rb
  spec/services/cfe/assets_payload_service_spec.rb
Labels: Approved, UAT

#1774 El 1616 joint owned other than landlord question
  app/controllers/flow/handler.rb
  app/forms/property_landlord_form.rb
  app/lib/steps/logic.rb
  app/lib/steps/outgoings_section.rb
  app/lib/steps/property_section.rb
  app/views/question_flow/property_landlord.html.slim
  config/allowed_analytics_pages.yml
  config/locales/en.yml
  spec/forms/property_landlord_form_spec.rb
Labels: Approved, UAT

#1773 EL-2119: add id to track when user clicksasylum support evidence deta…
  config/locales/en.yml
Labels: Approved

#1775 EL-1947: Shared Ownership - exit page
  app/controllers/feedbacks_controller.rb
  app/controllers/flow/handler.rb
  app/controllers/question_flow_controller.rb
  app/forms/cannot_use_service_form.rb
  app/lib/steps/logic.rb
  app/lib/steps/outgoings_section.rb
  app/lib/steps/property_section.rb
  app/services/external_link_service.rb
  app/views/question_flow/cannot_use_service.html.slim
  config/allowed_analytics_event_types.yml
  config/allowed_analytics_pages.yml
  config/locales/en.yml
  spec/controllers/feedbacks_controller_spec.rb
  spec/forms/property_landlord_form_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#1781 El 1581 cya shared ownership
  app/models/check.rb
  app/services/check_answers/sections/housing_and_property.rb
  config/locales/en.yml
  spec/flows/household_flow_spec.rb
  spec/flows/outgoings_flow_spec.rb
  spec/forms/housing_costs_form_spec.rb
  spec/forms/mortgage_or_loan_payment_form_spec.rb
  spec/forms/property_entry_form_spec.rb
  spec/views/check_answers_page/client_content/housing_benefit_spec.rb
  spec/views/check_answers_page/client_content/property_spec.rb
Labels: Approved, UAT

#1795 EL-2140 tidy up feature flags
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
Labels: Approved

#1790 EL-2155 parallel test runs
  README.md
Labels: Approved

#1797 EL-2168: Shared ownership - start page content
  app/views/start/index.html.slim
  config/locales/en.yml
Labels: Approved, UAT

#1796 EL-1970: Update footer crest for `maintenance mode`, `500`, `422`, `404` pages
  public/crest.svg
Labels: Approved, UAT

#1793 EL-2164 update shared costs page design
  app/forms/shared_ownership_housing_costs_form.rb
  app/views/question_flow/shared_ownership_housing_costs.html.slim
  config/locales/en.yml
  spec/flows/household_flow_spec.rb
Labels: Approved, UAT

#1799 EL-2167: Shared Ownership - send housing benefit to CFE
  app/services/cfe_param_builders/regular_transactions.rb
  spec/services/cfe/regular_transactions_payload_service_spec.rb
Labels: Approved, UAT

#1783 EL-1582: Shared Ownership, Results page (Household monthly outgoings)
  app/helpers/results_helper.rb
  app/models/calculation_result.rb
  app/models/cfe_result.rb
  app/models/check.rb
  app/views/results/_outgoings_row.html.slim
  config/locales/en.yml
  spec/views/results_page/housing_outgoings_content_spec.rb
Labels: Approved, UAT

#1806 EL-2197 manual upgrade of puppeteer to 24.4.0
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1808 EL-2195 Dependent Income Validation
  app/models/dependant_income_model.rb
  config/locales/en.yml
  spec/forms/dependant_income_details_form_spec.rb
  spec/models/dependant_income_model_spec.rb
  spec/models/housing_costs_form_spec.rb
Labels: bug, Approved, UAT

#1798 EL-2170 Lock govuk fronted version
  package.json
  yarn.lock
Labels: Approved, UAT

#1809 El 2166 additional properties exit page
  Gemfile
  Gemfile.lock
  app/controllers/cannot_use_service_controller.rb
  app/controllers/change_answers_controller.rb
  app/controllers/forms_controller.rb
  app/lib/steps/helper.rb
  app/views/cannot_use_service/additional_properties.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/controllers/cannot_use_service_controller_spec.rb
  spec/flows/cannot_use_service_flow_spec.rb
  spec/support/flow_helpers.rb
  spec/views/cannot_use_service_page/additional_properties_spec.rb
Labels: Approved
