Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2025-07, with the labels that each got.

#1910 Puppeteer 24111
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1905 el-2391: remove references to early_eligibility_selection
  app/controllers/results_controller.rb
  app/models/calculation_result.rb
  app/views/results/_capital_table.html.slim
  app/views/results/_outgoings_table.html.slim
  app/views/results/_summary.html.slim
Labels: Approved, UAT

#1918 EL-2485: Update puppeteer to 24.11.2
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved

#1923 EL-2503: Update puppeteer to 24.12.1
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Ready For Review

#1924 EL-2268: Delete SQL attack data from AnalyticEvent table
  lib/tasks/delete_analytics_event_via_assessment_code.rake
  lib/tasks/delete_analytics_event_via_time_frame_open.rake
  lib/tasks/delete_feedback.rake
Labels: Approved

#1940 EL-2551: Update "puppeteer" to "24.15.0"
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved
