Repository ministryofjustice/laa-check-client-qualifies, pull requests merged in 2025-04, with the labels that each got.

#1810 Bugfix/EL-2205 validate housing payments
  app/forms/base_housing_costs_form.rb
  app/forms/housing_costs_form.rb
  spec/forms/housing_costs_form_spec.rb
  spec/models/housing_costs_form_spec.rb
Labels: bug, Approved, UAT

#1823 EL-2239: Fix CCQ pipeline due to failing threshold tests
  spec/forms/dependant_details_form_spec.rb
  spec/views/results_page/housing_outgoings_content_spec.rb
Labels: Approved

#1825 EL-2158: Remove `thresholds_2025` feature flag
  app/lib/feature_flags.rb
  app/models/dependant_income_model.rb
  spec/end_to_end/without_partner_spec.rb
  spec/forms/dependant_income_details_form_spec.rb
  spec/models/dependant_income_model_spec.rb
  spec/views/results_page/client_financial_content_spec.rb
Labels: Approved, UAT

#1814 El 1562 remove unused translations
  config/locales/en.yml
Labels: Approved, UAT

#1816 EL-2194 show exit page when multiple owners
  app/controllers/change_answers_controller.rb
  spec/flows/change_answers_flow_spec.rb
Labels: Approved, UAT

#1818 EL-2222 Shared ownership Check Answers flow
  app/controllers/change_answers_controller.rb
  app/lib/steps/helper.rb
  spec/flows/change_answers_flow_spec.rb
  spec/flows/shared_ownership_flow_spec.rb
  spec/support/flow_helpers.rb
Labels: Approved, UAT

#1826 EL-2159: refactor cannot use service page
  app/controllers/cannot_use_service_controller.rb
  app/controllers/change_answers_controller.rb
  app/controllers/flow/handler.rb
  app/controllers/question_flow_controller.rb
  app/forms/cannot_use_service_form.rb
  app/lib/steps/helper.rb
  app/lib/steps/logic.rb
  app/lib/steps/outgoings_section.rb
  app/lib/steps/property_section.rb
  app/views/cannot_use_service/show.html.slim
  config/locales/en.yml
  config/routes.rb
  spec/controllers/cannot_use_service_controller_spec.rb
  spec/flows/cannot_use_service_flow_spec.rb
  spec/forms/property_landlord_form_spec.rb
  spec/views/cannot_use_service_page/additional_properties_spec.rb
  spec/views/cannot_use_service_page/show_spec.rb
Labels: Approved, UAT

#1830 EL-2142: Turn on `shared_ownership` for CCQ metabase testing
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
Labels: Approved

#1829 EL-2226: Bump to `moj-frontend` 5.1.0
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/button-group-custom.scss
  app/assets/stylesheets/feedback.scss
  app/assets/stylesheets/results.scss
  app/assets/stylesheets/suggestions.scss
  package.json
  yarn.lock
Labels: Approved, UAT

#1840 Manual upgrade of puppeteer to 24.6.1
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1841 EL-2259: Remove `back` link on 'cannot_use_service` page
  app/views/cannot_use_service/show.html.slim
  app/views/question_flow/cannot_use_service.html.slim
  spec/flows/cannot_use_service_flow_spec.rb
Labels: Approved, UAT

#1838 EL-2260: Add watermarks to english and welsh CW forms when its shared ownership
  app/services/controlled_work_document_population_service.rb
  lib/CWforms_SharedOwnership_english.pdf
  lib/CWforms_SharedOwnership_welsh.pdf
  spec/services/controlled_work_document_population_service_spec.rb
Labels: Approved, UAT

#1854 Puppeteer 2472
  .circleci/config.yml
  .github/workflows/browser_tools_docker_image.yml
  Dockerfile_browser_tools.dockerfile
  package.json
  yarn.lock
Labels: Approved, UAT

#1846 El 1786 remove ee code
  app/controllers/change_answers_controller.rb
  app/controllers/checks_controller.rb
  app/controllers/flow/handler.rb
  app/controllers/forms_controller.rb
  app/controllers/question_flow_controller.rb
  app/forms/ineligible_gross_income_form.rb
  app/lib/feature_flags.rb
  app/lib/steps/helper.rb
  app/lib/steps/logic.rb
  app/models/cfe_result.rb
  app/models/check.rb
  app/services/check_answers/section_lister_service.rb
  app/services/journey_logger_service.rb
  app/views/question_flow/_early_result_banner.html.slim
  app/views/question_flow/ineligible_gross_income.html.slim
  app/views/results/show.html.slim
  config/locales/en.yml
  helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
  helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
  helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
  spec/controllers/results_controller_spec.rb
  spec/end_to_end/result_page_variations_spec.rb
  spec/features/provider_login_spec.rb
  spec/flows/cannot_use_service_flow_spec.rb
  spec/flows/change_answers_flow_spec.rb
  spec/flows/early_result_change_answers_flow_spec.rb
  spec/flows/early_result_spec.rb
  spec/flows/shared_ownership_flow_spec.rb
  spec/rails_helper.rb
  spec/services/journey_logger_service_spec.rb
Labels: Approved, UAT
